[
{'donor-country': 'all', 'name': 'core', 'value': 484940477},
{'donor-country': 'all', 'name': 'trust funds', 'value': 180733458},
{'donor-country': 'all', 'name': 'unv', 'value': 3691119},
{'donor-country': 'all', 'name': 'cost sharing', 'value': 1648373742},
{'donor-country': 'all', 'name': 'thematic trust funds', 'value': 43250183},
{'donor-country': 'all', 'name': 'non-core', 'value': 1895340621},
{'donor-country': 'all', 'name': 'special activities', 'value': 19292119},
{'donor-country': 'DZA', 'name': 'core', 'value': 0},
{'donor-country': 'DZA', 'name': 'trust funds', 'value': 76575},
{'donor-country': 'DZA', 'name': 'unv', 'value': 0},
{'donor-country': 'DZA', 'name': 'cost sharing', 'value': 715655},
{'donor-country': 'DZA', 'name': 'thematic trust funds', 'value': 0},
{'donor-country': 'DZA', 'name': 'non-core', 'value': 792230},
{'donor-country': 'DZA', 'name': 'special activities', 'value': 0},
{'donor-country': 'LIE', 'name': 'core', 'value': 27716},
{'donor-country': 'LIE', 'name': 'trust funds', 'value': 0},
{'donor-country': 'LIE', 'name': 'unv', 'value': 0},
{'donor-country': 'LIE', 'name': 'cost sharing', 'value': 0},
{'donor-country': 'LIE', 'name': 'thematic trust funds', 'value': 0},
{'donor-country': 'LIE', 'name': 'non-core', 'value': 0},
{'donor-country': 'LIE', 'name': 'special activities', 'value': 0},
{'donor-country': 'EGY', 'name': 'core', 'value': 0},
{'donor-country': 'EGY', 'name': 'trust funds', 'value': 0},
{'donor-country': 'EGY', 'name': 'unv', 'value': 0},
{'donor-country': 'EGY', 'name': 'cost sharing', 'value': 37380780},
{'donor-country': 'EGY', 'name': 'thematic trust funds', 'value': 0},
{'donor-country': 'EGY', 'name': 'non-core', 'value': 37380780},
{'donor-country': 'EGY', 'name': 'special activities', 'value': 0},
{'donor-country': 'BGD', 'name': 'core', 'value': 414230},
{'donor-country': 'BGD', 'name': 'trust funds', 'value': 0},
{'donor-country': 'BGD', 'name': 'unv', 'value': 0},
{'donor-country': 'BGD', 'name': 'cost sharing', 'value': 0},
{'donor-country': 'BGD', 'name': 'thematic trust funds', 'value': 0},
{'donor-country': 'BGD', 'name': 'non-core', 'value': 0},
{'donor-country': 'BGD', 'name': 'special activities', 'value': 0},
{'donor-country': 'QAT', 'name': 'core', 'value': 0},
{'donor-country': 'QAT', 'name': 'trust funds', 'value': 0},
{'donor-country': 'QAT', 'name': 'unv', 'value': 0},
{'donor-country': 'QAT', 'name': 'cost sharing', 'value': 0},
{'donor-country': 'QAT', 'name': 'thematic trust funds', 'value': 0},
{'donor-country': 'QAT', 'name': 'non-core', 'value': 0},
{'donor-country': 'QAT', 'name': 'special activities', 'value': 0},
{'donor-country': 'SOM', 'name': 'core', 'value': 0},
{'donor-country': 'SOM', 'name': 'trust funds', 'value': 0},
{'donor-country': 'SOM', 'name': 'unv', 'value': 0},
{'donor-country': 'SOM', 'name': 'cost sharing', 'value': 0},
{'donor-country': 'SOM', 'name': 'thematic trust funds', 'value': 0},
{'donor-country': 'SOM', 'name': 'non-core', 'value': 0},
{'donor-country': 'SOM', 'name': 'special activities', 'value': 0},
{'donor-country': 'NAN', 'name': 'core', 'value': 0},
{'donor-country': 'NAN', 'name': 'trust funds', 'value': 0},
{'donor-country': 'NAN', 'name': 'unv', 'value': 0},
{'donor-country': 'NAN', 'name': 'cost sharing', 'value': 0},
{'donor-country': 'NAN', 'name': 'thematic trust funds', 'value': 0},
{'donor-country': 'NAN', 'name': 'non-core', 'value': 0},
{'donor-country': 'NAN', 'name': 'special activities', 'value': 0},
{'donor-country': 'NAM', 'name': 'core', 'value': 0},
{'donor-country': 'NAM', 'name': 'trust funds', 'value': 0},
{'donor-country': 'NAM', 'name': 'unv', 'value': 0},
{'donor-country': 'NAM', 'name': 'cost sharing', 'value': 0},
{'donor-country': 'NAM', 'name': 'thematic trust funds', 'value': 0},
{'donor-country': 'NAM', 'name': 'non-core', 'value': 0},
{'donor-country': 'NAM', 'name': 'special activities', 'value': 0},
{'donor-country': 'BGR', 'name': 'core', 'value': 0},
{'donor-country': 'BGR', 'name': 'trust funds', 'value': 0},
{'donor-country': 'BGR', 'name': 'unv', 'value': 0},
{'donor-country': 'BGR', 'name': 'cost sharing', 'value': 0},
{'donor-country': 'BGR', 'name': 'thematic trust funds', 'value': 0},
{'donor-country': 'BGR', 'name': 'non-core', 'value': 0},
{'donor-country': 'BGR', 'name': 'special activities', 'value': 0},
{'donor-country': 'BOL', 'name': 'core', 'value': 0},
{'donor-country': 'BOL', 'name': 'trust funds', 'value': 0},
{'donor-country': 'BOL', 'name': 'unv', 'value': 0},
{'donor-country': 'BOL', 'name': 'cost sharing', 'value': 647852},
{'donor-country': 'BOL', 'name': 'thematic trust funds', 'value': 0},
{'donor-country': 'BOL', 'name': 'non-core', 'value': 647852},
{'donor-country': 'BOL', 'name': 'special activities', 'value': 0},
{'donor-country': 'GHA', 'name': 'core', 'value': 0},
{'donor-country': 'GHA', 'name': 'trust funds', 'value': 0},
{'donor-country': 'GHA', 'name': 'unv', 'value': 0},
{'donor-country': 'GHA', 'name': 'cost sharing', 'value': 0},
{'donor-country': 'GHA', 'name': 'thematic trust funds', 'value': 0},
{'donor-country': 'GHA', 'name': 'non-core', 'value': 0},
{'donor-country': 'GHA', 'name': 'special activities', 'value': 0},
{'donor-country': 'SIK', 'name': 'core', 'value': 0},
{'donor-country': 'SIK', 'name': 'trust funds', 'value': 0},
{'donor-country': 'SIK', 'name': 'unv', 'value': 0},
{'donor-country': 'SIK', 'name': 'cost sharing', 'value': 0},
{'donor-country': 'SIK', 'name': 'thematic trust funds', 'value': 0},
{'donor-country': 'SIK', 'name': 'non-core', 'value': 0},
{'donor-country': 'SIK', 'name': 'special activities', 'value': 0},
{'donor-country': 'PAK', 'name': 'core', 'value': 543612},
{'donor-country': 'PAK', 'name': 'trust funds', 'value': 0},
{'donor-country': 'PAK', 'name': 'unv', 'value': 0},
{'donor-country': 'PAK', 'name': 'cost sharing', 'value': 848006},
{'donor-country': 'PAK', 'name': 'thematic trust funds', 'value': 0},
{'donor-country': 'PAK', 'name': 'non-core', 'value': 848006},
{'donor-country': 'PAK', 'name': 'special activities', 'value': 0},
{'donor-country': 'CPV', 'name': 'core', 'value': 0},
{'donor-country': 'CPV', 'name': 'trust funds', 'value': 0},
{'donor-country': 'CPV', 'name': 'unv', 'value': 0},
{'donor-country': 'CPV', 'name': 'cost sharing', 'value': 189192},
{'donor-country': 'CPV', 'name': 'thematic trust funds', 'value': 0},
{'donor-country': 'CPV', 'name': 'non-core', 'value': 189192},
{'donor-country': 'CPV', 'name': 'special activities', 'value': 0},
{'donor-country': 'JOR', 'name': 'core', 'value': 0},
{'donor-country': 'JOR', 'name': 'trust funds', 'value': 0},
{'donor-country': 'JOR', 'name': 'unv', 'value': 0},
{'donor-country': 'JOR', 'name': 'cost sharing', 'value': 511881},
{'donor-country': 'JOR', 'name': 'thematic trust funds', 'value': 0},
{'donor-country': 'JOR', 'name': 'non-core', 'value': 511881},
{'donor-country': 'JOR', 'name': 'special activities', 'value': 0},
{'donor-country': 'LBR', 'name': 'core', 'value': 0},
{'donor-country': 'LBR', 'name': 'trust funds', 'value': 0},
{'donor-country': 'LBR', 'name': 'unv', 'value': 0},
{'donor-country': 'LBR', 'name': 'cost sharing', 'value': 0},
{'donor-country': 'LBR', 'name': 'thematic trust funds', 'value': 0},
{'donor-country': 'LBR', 'name': 'non-core', 'value': 0},
{'donor-country': 'LBR', 'name': 'special activities', 'value': 0},
{'donor-country': 'MUS', 'name': 'core', 'value': 0},
{'donor-country': 'MUS', 'name': 'trust funds', 'value': 0},
{'donor-country': 'MUS', 'name': 'unv', 'value': 0},
{'donor-country': 'MUS', 'name': 'cost sharing', 'value': 153000},
{'donor-country': 'MUS', 'name': 'thematic trust funds', 'value': 0},
{'donor-country': 'MUS', 'name': 'non-core', 'value': 153000},
{'donor-country': 'MUS', 'name': 'special activities', 'value': 0},
{'donor-country': 'LBY', 'name': 'core', 'value': 0},
{'donor-country': 'LBY', 'name': 'trust funds', 'value': 0},
{'donor-country': 'LBY', 'name': 'unv', 'value': 0},
{'donor-country': 'LBY', 'name': 'cost sharing', 'value': 4663535},
{'donor-country': 'LBY', 'name': 'thematic trust funds', 'value': 0},
{'donor-country': 'LBY', 'name': 'non-core', 'value': 4663535},
{'donor-country': 'LBY', 'name': 'special activities', 'value': 0},
{'donor-country': 'MYS', 'name': 'core', 'value': 1075530},
{'donor-country': 'MYS', 'name': 'trust funds', 'value': 0},
{'donor-country': 'MYS', 'name': 'unv', 'value': 0},
{'donor-country': 'MYS', 'name': 'cost sharing', 'value': 0},
{'donor-country': 'MYS', 'name': 'thematic trust funds', 'value': 0},
{'donor-country': 'MYS', 'name': 'non-core', 'value': 0},
{'donor-country': 'MYS', 'name': 'special activities', 'value': 0},
{'donor-country': 'PRI', 'name': 'core', 'value': 0},
{'donor-country': 'PRI', 'name': 'trust funds', 'value': 0},
{'donor-country': 'PRI', 'name': 'unv', 'value': 0},
{'donor-country': 'PRI', 'name': 'cost sharing', 'value': 0},
{'donor-country': 'PRI', 'name': 'thematic trust funds', 'value': 0},
{'donor-country': 'PRI', 'name': 'non-core', 'value': 0},
{'donor-country': 'PRI', 'name': 'special activities', 'value': 0},
{'donor-country': 'PRK', 'name': 'core', 'value': 50481},
{'donor-country': 'PRK', 'name': 'trust funds', 'value': 0},
{'donor-country': 'PRK', 'name': 'unv', 'value': 0},
{'donor-country': 'PRK', 'name': 'cost sharing', 'value': 0},
{'donor-country': 'PRK', 'name': 'thematic trust funds', 'value': 0},
{'donor-country': 'PRK', 'name': 'non-core', 'value': 0},
{'donor-country': 'PRK', 'name': 'special activities', 'value': 0},
{'donor-country': 'TZA', 'name': 'core', 'value': 0},
{'donor-country': 'TZA', 'name': 'trust funds', 'value': 0},
{'donor-country': 'TZA', 'name': 'unv', 'value': 0},
{'donor-country': 'TZA', 'name': 'cost sharing', 'value': 170156},
{'donor-country': 'TZA', 'name': 'thematic trust funds', 'value': 0},
{'donor-country': 'TZA', 'name': 'non-core', 'value': 170156},
{'donor-country': 'TZA', 'name': 'special activities', 'value': 0},
{'donor-country': 'BWA', 'name': 'core', 'value': 171038},
{'donor-country': 'BWA', 'name': 'trust funds', 'value': 0},
{'donor-country': 'BWA', 'name': 'unv', 'value': 0},
{'donor-country': 'BWA', 'name': 'cost sharing', 'value': 2762769},
{'donor-country': 'BWA', 'name': 'thematic trust funds', 'value': 0},
{'donor-country': 'BWA', 'name': 'non-core', 'value': 2762769},
{'donor-country': 'BWA', 'name': 'special activities', 'value': 0},
{'donor-country': 'KHM', 'name': 'core', 'value': 326000},
{'donor-country': 'KHM', 'name': 'trust funds', 'value': 0},
{'donor-country': 'KHM', 'name': 'unv', 'value': 0},
{'donor-country': 'KHM', 'name': 'cost sharing', 'value': 0},
{'donor-country': 'KHM', 'name': 'thematic trust funds', 'value': 0},
{'donor-country': 'KHM', 'name': 'non-core', 'value': 0},
{'donor-country': 'KHM', 'name': 'special activities', 'value': 0},
{'donor-country': 'PRY', 'name': 'core', 'value': 0},
{'donor-country': 'PRY', 'name': 'trust funds', 'value': 0},
{'donor-country': 'PRY', 'name': 'unv', 'value': 0},
{'donor-country': 'PRY', 'name': 'cost sharing', 'value': 10790495},
{'donor-country': 'PRY', 'name': 'thematic trust funds', 'value': 0},
{'donor-country': 'PRY', 'name': 'non-core', 'value': 10790495},
{'donor-country': 'PRY', 'name': 'special activities', 'value': 0},
{'donor-country': 'HKG', 'name': 'core', 'value': 0},
{'donor-country': 'HKG', 'name': 'trust funds', 'value': 0},
{'donor-country': 'HKG', 'name': 'unv', 'value': 0},
{'donor-country': 'HKG', 'name': 'cost sharing', 'value': 0},
{'donor-country': 'HKG', 'name': 'thematic trust funds', 'value': 0},
{'donor-country': 'HKG', 'name': 'non-core', 'value': 0},
{'donor-country': 'HKG', 'name': 'special activities', 'value': 0},
{'donor-country': 'SAU', 'name': 'core', 'value': 2000000},
{'donor-country': 'SAU', 'name': 'trust funds', 'value': 0},
{'donor-country': 'SAU', 'name': 'unv', 'value': 0},
{'donor-country': 'SAU', 'name': 'cost sharing', 'value': 25749047},
{'donor-country': 'SAU', 'name': 'thematic trust funds', 'value': 0},
{'donor-country': 'SAU', 'name': 'non-core', 'value': 25749047},
{'donor-country': 'SAU', 'name': 'special activities', 'value': 0},
{'donor-country': 'LBN', 'name': 'core', 'value': 0},
{'donor-country': 'LBN', 'name': 'trust funds', 'value': 0},
{'donor-country': 'LBN', 'name': 'unv', 'value': 0},
{'donor-country': 'LBN', 'name': 'cost sharing', 'value': 8545988},
{'donor-country': 'LBN', 'name': 'thematic trust funds', 'value': 0},
{'donor-country': 'LBN', 'name': 'non-core', 'value': 8545988},
{'donor-country': 'LBN', 'name': 'special activities', 'value': 0},
{'donor-country': 'SVN', 'name': 'core', 'value': 0},
{'donor-country': 'SVN', 'name': 'trust funds', 'value': 0},
{'donor-country': 'SVN', 'name': 'unv', 'value': 0},
{'donor-country': 'SVN', 'name': 'cost sharing', 'value': 0},
{'donor-country': 'SVN', 'name': 'thematic trust funds', 'value': 0},
{'donor-country': 'SVN', 'name': 'non-core', 'value': 0},
{'donor-country': 'SVN', 'name': 'special activities', 'value': 0},
{'donor-country': 'BFA', 'name': 'core', 'value': 0},
{'donor-country': 'BFA', 'name': 'trust funds', 'value': 0},
{'donor-country': 'BFA', 'name': 'unv', 'value': 0},
{'donor-country': 'BFA', 'name': 'cost sharing', 'value': 163658},
{'donor-country': 'BFA', 'name': 'thematic trust funds', 'value': 0},
{'donor-country': 'BFA', 'name': 'non-core', 'value': 163658},
{'donor-country': 'BFA', 'name': 'special activities', 'value': 0},
{'donor-country': 'CHE', 'name': 'core', 'value': 63474388},
{'donor-country': 'CHE', 'name': 'trust funds', 'value': 410277},
{'donor-country': 'CHE', 'name': 'unv', 'value': 1240564},
{'donor-country': 'CHE', 'name': 'cost sharing', 'value': 23952529},
{'donor-country': 'CHE', 'name': 'thematic trust funds', 'value': 75000},
{'donor-country': 'CHE', 'name': 'non-core', 'value': 25636788},
{'donor-country': 'CHE', 'name': 'special activities', 'value': -41582},
{'donor-country': 'MRT', 'name': 'core', 'value': 407689},
{'donor-country': 'MRT', 'name': 'trust funds', 'value': 0},
{'donor-country': 'MRT', 'name': 'unv', 'value': 0},
{'donor-country': 'MRT', 'name': 'cost sharing', 'value': -4296},
{'donor-country': 'MRT', 'name': 'thematic trust funds', 'value': 0},
{'donor-country': 'MRT', 'name': 'non-core', 'value': -4296},
{'donor-country': 'MRT', 'name': 'special activities', 'value': 0},
{'donor-country': 'IFI_WB', 'name': 'core', 'value': 0},
{'donor-country': 'IFI_WB', 'name': 'trust funds', 'value': 0},
{'donor-country': 'IFI_WB', 'name': 'unv', 'value': 0},
{'donor-country': 'IFI_WB', 'name': 'cost sharing', 'value': 0},
{'donor-country': 'IFI_WB', 'name': 'thematic trust funds', 'value': 0},
{'donor-country': 'IFI_WB', 'name': 'non-core', 'value': 0},
{'donor-country': 'IFI_WB', 'name': 'special activities', 'value': 0},
{'donor-country': 'HRV', 'name': 'core', 'value': 0},
{'donor-country': 'HRV', 'name': 'trust funds', 'value': 0},
{'donor-country': 'HRV', 'name': 'unv', 'value': 0},
{'donor-country': 'HRV', 'name': 'cost sharing', 'value': 2133295},
{'donor-country': 'HRV', 'name': 'thematic trust funds', 'value': 0},
{'donor-country': 'HRV', 'name': 'non-core', 'value': 2133295},
{'donor-country': 'HRV', 'name': 'special activities', 'value': 0},
{'donor-country': 'CHL', 'name': 'core', 'value': 320000},
{'donor-country': 'CHL', 'name': 'trust funds', 'value': -1},
{'donor-country': 'CHL', 'name': 'unv', 'value': 0},
{'donor-country': 'CHL', 'name': 'cost sharing', 'value': 4603938},
{'donor-country': 'CHL', 'name': 'thematic trust funds', 'value': 0},
{'donor-country': 'CHL', 'name': 'non-core', 'value': 4603937},
{'donor-country': 'CHL', 'name': 'special activities', 'value': 0},
{'donor-country': 'CHN', 'name': 'core', 'value': 0},
{'donor-country': 'CHN', 'name': 'trust funds', 'value': 6151499},
{'donor-country': 'CHN', 'name': 'unv', 'value': 30000},
{'donor-country': 'CHN', 'name': 'cost sharing', 'value': 4703507},
{'donor-country': 'CHN', 'name': 'thematic trust funds', 'value': 0},
{'donor-country': 'CHN', 'name': 'non-core', 'value': 10885006},
{'donor-country': 'CHN', 'name': 'special activities', 'value': 0},
{'donor-country': 'KNA', 'name': 'core', 'value': 0},
{'donor-country': 'KNA', 'name': 'trust funds', 'value': 0},
{'donor-country': 'KNA', 'name': 'unv', 'value': 0},
{'donor-country': 'KNA', 'name': 'cost sharing', 'value': 0},
{'donor-country': 'KNA', 'name': 'thematic trust funds', 'value': 0},
{'donor-country': 'KNA', 'name': 'non-core', 'value': 0},
{'donor-country': 'KNA', 'name': 'special activities', 'value': 0},
{'donor-country': 'SLE', 'name': 'core', 'value': 0},
{'donor-country': 'SLE', 'name': 'trust funds', 'value': 0},
{'donor-country': 'SLE', 'name': 'unv', 'value': 0},
{'donor-country': 'SLE', 'name': 'cost sharing', 'value': 0},
{'donor-country': 'SLE', 'name': 'thematic trust funds', 'value': 0},
{'donor-country': 'SLE', 'name': 'non-core', 'value': 0},
{'donor-country': 'SLE', 'name': 'special activities', 'value': 0},
{'donor-country': 'JAM', 'name': 'core', 'value': 56630},
{'donor-country': 'JAM', 'name': 'trust funds', 'value': 0},
{'donor-country': 'JAM', 'name': 'unv', 'value': 0},
{'donor-country': 'JAM', 'name': 'cost sharing', 'value': 0},
{'donor-country': 'JAM', 'name': 'thematic trust funds', 'value': 0},
{'donor-country': 'JAM', 'name': 'non-core', 'value': 0},
{'donor-country': 'JAM', 'name': 'special activities', 'value': 0},
{'donor-country': 'SMR', 'name': 'core', 'value': 0},
{'donor-country': 'SMR', 'name': 'trust funds', 'value': 0},
{'donor-country': 'SMR', 'name': 'unv', 'value': 0},
{'donor-country': 'SMR', 'name': 'cost sharing', 'value': 0},
{'donor-country': 'SMR', 'name': 'thematic trust funds', 'value': 0},
{'donor-country': 'SMR', 'name': 'non-core', 'value': 0},
{'donor-country': 'SMR', 'name': 'special activities', 'value': 0},
{'donor-country': 'DJI', 'name': 'core', 'value': 0},
{'donor-country': 'DJI', 'name': 'trust funds', 'value': 0},
{'donor-country': 'DJI', 'name': 'unv', 'value': 0},
{'donor-country': 'DJI', 'name': 'cost sharing', 'value': 816462},
{'donor-country': 'DJI', 'name': 'thematic trust funds', 'value': 0},
{'donor-country': 'DJI', 'name': 'non-core', 'value': 816462},
{'donor-country': 'DJI', 'name': 'special activities', 'value': 0},
{'donor-country': 'GIN', 'name': 'core', 'value': 0},
{'donor-country': 'GIN', 'name': 'trust funds', 'value': 0},
{'donor-country': 'GIN', 'name': 'unv', 'value': 0},
{'donor-country': 'GIN', 'name': 'cost sharing', 'value': 300000},
{'donor-country': 'GIN', 'name': 'thematic trust funds', 'value': 0},
{'donor-country': 'GIN', 'name': 'non-core', 'value': 300000},
{'donor-country': 'GIN', 'name': 'special activities', 'value': 0},
{'donor-country': 'FIN', 'name': 'core', 'value': 30261348},
{'donor-country': 'FIN', 'name': 'trust funds', 'value': 4259304},
{'donor-country': 'FIN', 'name': 'unv', 'value': 0},
{'donor-country': 'FIN', 'name': 'cost sharing', 'value': 6445717},
{'donor-country': 'FIN', 'name': 'thematic trust funds', 'value': 1277203},
{'donor-country': 'FIN', 'name': 'non-core', 'value': 14536502},
{'donor-country': 'FIN', 'name': 'special activities', 'value': 2554278},
{'donor-country': 'URY', 'name': 'core', 'value': 583365},
{'donor-country': 'URY', 'name': 'trust funds', 'value': 561901},
{'donor-country': 'URY', 'name': 'unv', 'value': 0},
{'donor-country': 'URY', 'name': 'cost sharing', 'value': 8635154},
{'donor-country': 'URY', 'name': 'thematic trust funds', 'value': 0},
{'donor-country': 'URY', 'name': 'non-core', 'value': 9197055},
{'donor-country': 'URY', 'name': 'special activities', 'value': 0},
{'donor-country': 'THA', 'name': 'core', 'value': 865112},
{'donor-country': 'THA', 'name': 'trust funds', 'value': 0},
{'donor-country': 'THA', 'name': 'unv', 'value': 0},
{'donor-country': 'THA', 'name': 'cost sharing', 'value': 159898},
{'donor-country': 'THA', 'name': 'thematic trust funds', 'value': 0},
{'donor-country': 'THA', 'name': 'non-core', 'value': 159898},
{'donor-country': 'THA', 'name': 'special activities', 'value': 0},
{'donor-country': 'SYC', 'name': 'core', 'value': 0},
{'donor-country': 'SYC', 'name': 'trust funds', 'value': 0},
{'donor-country': 'SYC', 'name': 'unv', 'value': 0},
{'donor-country': 'SYC', 'name': 'cost sharing', 'value': 0},
{'donor-country': 'SYC', 'name': 'thematic trust funds', 'value': 0},
{'donor-country': 'SYC', 'name': 'non-core', 'value': 0},
{'donor-country': 'SYC', 'name': 'special activities', 'value': 0},
{'donor-country': 'NPL', 'name': 'core', 'value': 0},
{'donor-country': 'NPL', 'name': 'trust funds', 'value': 334},
{'donor-country': 'NPL', 'name': 'unv', 'value': 0},
{'donor-country': 'NPL', 'name': 'cost sharing', 'value': 1546611},
{'donor-country': 'NPL', 'name': 'thematic trust funds', 'value': 0},
{'donor-country': 'NPL', 'name': 'non-core', 'value': 1546945},
{'donor-country': 'NPL', 'name': 'special activities', 'value': 0},
{'donor-country': 'LAO', 'name': 'core', 'value': 0},
{'donor-country': 'LAO', 'name': 'trust funds', 'value': 2000},
{'donor-country': 'LAO', 'name': 'unv', 'value': 0},
{'donor-country': 'LAO', 'name': 'cost sharing', 'value': 0},
{'donor-country': 'LAO', 'name': 'thematic trust funds', 'value': 0},
{'donor-country': 'LAO', 'name': 'non-core', 'value': 2000},
{'donor-country': 'LAO', 'name': 'special activities', 'value': 0},
{'donor-country': 'YEM', 'name': 'core', 'value': 0},
{'donor-country': 'YEM', 'name': 'trust funds', 'value': 0},
{'donor-country': 'YEM', 'name': 'unv', 'value': 0},
{'donor-country': 'YEM', 'name': 'cost sharing', 'value': 112155},
{'donor-country': 'YEM', 'name': 'thematic trust funds', 'value': 0},
{'donor-country': 'YEM', 'name': 'non-core', 'value': 112155},
{'donor-country': 'YEM', 'name': 'special activities', 'value': 0},
{'donor-country': 'MDTF1', 'name': 'core', 'value': 0},
{'donor-country': 'MDTF1', 'name': 'trust funds', 'value': 4745223},
{'donor-country': 'MDTF1', 'name': 'unv', 'value': 103435},
{'donor-country': 'MDTF1', 'name': 'cost sharing', 'value': 203427228},
{'donor-country': 'MDTF1', 'name': 'thematic trust funds', 'value': 650884},
{'donor-country': 'MDTF1', 'name': 'non-core', 'value': 208845313},
{'donor-country': 'MDTF1', 'name': 'special activities', 'value': -81457},
{'donor-country': 'ZAF', 'name': 'core', 'value': 749937},
{'donor-country': 'ZAF', 'name': 'trust funds', 'value': 1006794},
{'donor-country': 'ZAF', 'name': 'unv', 'value': 0},
{'donor-country': 'ZAF', 'name': 'cost sharing', 'value': 1196211},
{'donor-country': 'ZAF', 'name': 'thematic trust funds', 'value': 0},
{'donor-country': 'ZAF', 'name': 'non-core', 'value': 2203005},
{'donor-country': 'ZAF', 'name': 'special activities', 'value': 0},
{'donor-country': 'KIR', 'name': 'core', 'value': 0},
{'donor-country': 'KIR', 'name': 'trust funds', 'value': 0},
{'donor-country': 'KIR', 'name': 'unv', 'value': 0},
{'donor-country': 'KIR', 'name': 'cost sharing', 'value': 0},
{'donor-country': 'KIR', 'name': 'thematic trust funds', 'value': 0},
{'donor-country': 'KIR', 'name': 'non-core', 'value': 0},
{'donor-country': 'KIR', 'name': 'special activities', 'value': 0},
{'donor-country': 'PHL', 'name': 'core', 'value': 507454},
{'donor-country': 'PHL', 'name': 'trust funds', 'value': 0},
{'donor-country': 'PHL', 'name': 'unv', 'value': 0},
{'donor-country': 'PHL', 'name': 'cost sharing', 'value': 31996},
{'donor-country': 'PHL', 'name': 'thematic trust funds', 'value': 0},
{'donor-country': 'PHL', 'name': 'non-core', 'value': 31996},
{'donor-country': 'PHL', 'name': 'special activities', 'value': 0},
{'donor-country': 'GAB', 'name': 'core', 'value': 511022},
{'donor-country': 'GAB', 'name': 'trust funds', 'value': 0},
{'donor-country': 'GAB', 'name': 'unv', 'value': 0},
{'donor-country': 'GAB', 'name': 'cost sharing', 'value': 2340951},
{'donor-country': 'GAB', 'name': 'thematic trust funds', 'value': 0},
{'donor-country': 'GAB', 'name': 'non-core', 'value': 2340951},
{'donor-country': 'GAB', 'name': 'special activities', 'value': 0},
{'donor-country': 'SYR', 'name': 'core', 'value': 0},
{'donor-country': 'SYR', 'name': 'trust funds', 'value': 0},
{'donor-country': 'SYR', 'name': 'unv', 'value': 0},
{'donor-country': 'SYR', 'name': 'cost sharing', 'value': -173298},
{'donor-country': 'SYR', 'name': 'thematic trust funds', 'value': 0},
{'donor-country': 'SYR', 'name': 'non-core', 'value': -173298},
{'donor-country': 'SYR', 'name': 'special activities', 'value': 0},
{'donor-country': 'NIC', 'name': 'core', 'value': 170000},
{'donor-country': 'NIC', 'name': 'trust funds', 'value': 0},
{'donor-country': 'NIC', 'name': 'unv', 'value': 0},
{'donor-country': 'NIC', 'name': 'cost sharing', 'value': 1493853},
{'donor-country': 'NIC', 'name': 'thematic trust funds', 'value': 0},
{'donor-country': 'NIC', 'name': 'non-core', 'value': 1493853},
{'donor-country': 'NIC', 'name': 'special activities', 'value': 0},
{'donor-country': 'KAZ', 'name': 'core', 'value': 0},
{'donor-country': 'KAZ', 'name': 'trust funds', 'value': 0},
{'donor-country': 'KAZ', 'name': 'unv', 'value': 0},
{'donor-country': 'KAZ', 'name': 'cost sharing', 'value': 2362874},
{'donor-country': 'KAZ', 'name': 'thematic trust funds', 'value': 0},
{'donor-country': 'KAZ', 'name': 'non-core', 'value': 2362874},
{'donor-country': 'KAZ', 'name': 'special activities', 'value': 0},
{'donor-country': 'TCA', 'name': 'core', 'value': 0},
{'donor-country': 'TCA', 'name': 'trust funds', 'value': 0},
{'donor-country': 'TCA', 'name': 'unv', 'value': 0},
{'donor-country': 'TCA', 'name': 'cost sharing', 'value': -8},
{'donor-country': 'TCA', 'name': 'thematic trust funds', 'value': 0},
{'donor-country': 'TCA', 'name': 'non-core', 'value': -8},
{'donor-country': 'TCA', 'name': 'special activities', 'value': 0},
{'donor-country': 'ZAR', 'name': 'core', 'value': 534523},
{'donor-country': 'ZAR', 'name': 'trust funds', 'value': 0},
{'donor-country': 'ZAR', 'name': 'unv', 'value': 0},
{'donor-country': 'ZAR', 'name': 'cost sharing', 'value': 0},
{'donor-country': 'ZAR', 'name': 'thematic trust funds', 'value': 0},
{'donor-country': 'ZAR', 'name': 'non-core', 'value': 0},
{'donor-country': 'ZAR', 'name': 'special activities', 'value': 0},
{'donor-country': 'PYF', 'name': 'core', 'value': 0},
{'donor-country': 'PYF', 'name': 'trust funds', 'value': 0},
{'donor-country': 'PYF', 'name': 'unv', 'value': 0},
{'donor-country': 'PYF', 'name': 'cost sharing', 'value': 0},
{'donor-country': 'PYF', 'name': 'thematic trust funds', 'value': 0},
{'donor-country': 'PYF', 'name': 'non-core', 'value': 0},
{'donor-country': 'PYF', 'name': 'special activities', 'value': 0},
{'donor-country': 'NIU', 'name': 'core', 'value': 20686},
{'donor-country': 'NIU', 'name': 'trust funds', 'value': 0},
{'donor-country': 'NIU', 'name': 'unv', 'value': 0},
{'donor-country': 'NIU', 'name': 'cost sharing', 'value': 0},
{'donor-country': 'NIU', 'name': 'thematic trust funds', 'value': 0},
{'donor-country': 'NIU', 'name': 'non-core', 'value': 0},
{'donor-country': 'NIU', 'name': 'special activities', 'value': 0},
{'donor-country': 'DMA', 'name': 'core', 'value': 0},
{'donor-country': 'DMA', 'name': 'trust funds', 'value': 0},
{'donor-country': 'DMA', 'name': 'unv', 'value': 0},
{'donor-country': 'DMA', 'name': 'cost sharing', 'value': 0},
{'donor-country': 'DMA', 'name': 'thematic trust funds', 'value': 0},
{'donor-country': 'DMA', 'name': 'non-core', 'value': 0},
{'donor-country': 'DMA', 'name': 'special activities', 'value': 0},
{'donor-country': 'BEN', 'name': 'core', 'value': 618531},
{'donor-country': 'BEN', 'name': 'trust funds', 'value': 0},
{'donor-country': 'BEN', 'name': 'unv', 'value': 0},
{'donor-country': 'BEN', 'name': 'cost sharing', 'value': 121078},
{'donor-country': 'BEN', 'name': 'thematic trust funds', 'value': 0},
{'donor-country': 'BEN', 'name': 'non-core', 'value': 121078},
{'donor-country': 'BEN', 'name': 'special activities', 'value': 0},
{'donor-country': 'NGA', 'name': 'core', 'value': 0},
{'donor-country': 'NGA', 'name': 'trust funds', 'value': -284965},
{'donor-country': 'NGA', 'name': 'unv', 'value': 0},
{'donor-country': 'NGA', 'name': 'cost sharing', 'value': 10214169},
{'donor-country': 'NGA', 'name': 'thematic trust funds', 'value': 0},
{'donor-country': 'NGA', 'name': 'non-core', 'value': 9929204},
{'donor-country': 'NGA', 'name': 'special activities', 'value': 0},
{'donor-country': 'BEL', 'name': 'core', 'value': 0},
{'donor-country': 'BEL', 'name': 'trust funds', 'value': -108942},
{'donor-country': 'BEL', 'name': 'unv', 'value': 729000},
{'donor-country': 'BEL', 'name': 'cost sharing', 'value': 3601075},
{'donor-country': 'BEL', 'name': 'thematic trust funds', 'value': 794702},
{'donor-country': 'BEL', 'name': 'non-core', 'value': 5015835},
{'donor-country': 'BEL', 'name': 'special activities', 'value': 0},
{'donor-country': 'PRIV_NATL 1', 'name': 'core', 'value': 0},
{'donor-country': 'PRIV_NATL 1', 'name': 'trust funds', 'value': -261},
{'donor-country': 'PRIV_NATL 1', 'name': 'unv', 'value': 0},
{'donor-country': 'PRIV_NATL 1', 'name': 'cost sharing', 'value': 17299539},
{'donor-country': 'PRIV_NATL 1', 'name': 'thematic trust funds', 'value': 1930},
{'donor-country': 'PRIV_NATL 1', 'name': 'non-core', 'value': 17301208},
{'donor-country': 'PRIV_NATL 1', 'name': 'special activities', 'value': 0},
{'donor-country': 'DEU', 'name': 'core', 'value': 0},
{'donor-country': 'DEU', 'name': 'trust funds', 'value': 30780917},
{'donor-country': 'DEU', 'name': 'unv', 'value': 3752744},
{'donor-country': 'DEU', 'name': 'cost sharing', 'value': 6299003},
{'donor-country': 'DEU', 'name': 'thematic trust funds', 'value': 4471385},
{'donor-country': 'DEU', 'name': 'non-core', 'value': 49228961},
{'donor-country': 'DEU', 'name': 'special activities', 'value': 3924912},
{'donor-country': 'LKA', 'name': 'core', 'value': 6740},
{'donor-country': 'LKA', 'name': 'trust funds', 'value': 0},
{'donor-country': 'LKA', 'name': 'unv', 'value': 0},
{'donor-country': 'LKA', 'name': 'cost sharing', 'value': 0},
{'donor-country': 'LKA', 'name': 'thematic trust funds', 'value': 0},
{'donor-country': 'LKA', 'name': 'non-core', 'value': 0},
{'donor-country': 'LKA', 'name': 'special activities', 'value': 0},
{'donor-country': 'GBR', 'name': 'core', 'value': 45681063},
{'donor-country': 'GBR', 'name': 'trust funds', 'value': -9732079},
{'donor-country': 'GBR', 'name': 'unv', 'value': 0},
{'donor-country': 'GBR', 'name': 'cost sharing', 'value': 82433612},
{'donor-country': 'GBR', 'name': 'thematic trust funds', 'value': 5596486},
{'donor-country': 'GBR', 'name': 'non-core', 'value': 79885233},
{'donor-country': 'GBR', 'name': 'special activities', 'value': 1587214},
{'donor-country': 'GUY', 'name': 'core', 'value': 24068},
{'donor-country': 'GUY', 'name': 'trust funds', 'value': 0},
{'donor-country': 'GUY', 'name': 'unv', 'value': 0},
{'donor-country': 'GUY', 'name': 'cost sharing', 'value': 0},
{'donor-country': 'GUY', 'name': 'thematic trust funds', 'value': 0},
{'donor-country': 'GUY', 'name': 'non-core', 'value': 0},
{'donor-country': 'GUY', 'name': 'special activities', 'value': 0},
{'donor-country': 'CRI', 'name': 'core', 'value': 380288},
{'donor-country': 'CRI', 'name': 'trust funds', 'value': 0},
{'donor-country': 'CRI', 'name': 'unv', 'value': 0},
{'donor-country': 'CRI', 'name': 'cost sharing', 'value': 0},
{'donor-country': 'CRI', 'name': 'thematic trust funds', 'value': 0},
{'donor-country': 'CRI', 'name': 'non-core', 'value': 0},
{'donor-country': 'CRI', 'name': 'special activities', 'value': 0},
{'donor-country': 'CMR', 'name': 'core', 'value': 330204},
{'donor-country': 'CMR', 'name': 'trust funds', 'value': 0},
{'donor-country': 'CMR', 'name': 'unv', 'value': 0},
{'donor-country': 'CMR', 'name': 'cost sharing', 'value': 0},
{'donor-country': 'CMR', 'name': 'thematic trust funds', 'value': 0},
{'donor-country': 'CMR', 'name': 'non-core', 'value': 0},
{'donor-country': 'CMR', 'name': 'special activities', 'value': 0},
{'donor-country': 'MAR', 'name': 'core', 'value': 0},
{'donor-country': 'MAR', 'name': 'trust funds', 'value': 0},
{'donor-country': 'MAR', 'name': 'unv', 'value': 0},
{'donor-country': 'MAR', 'name': 'cost sharing', 'value': 10762031},
{'donor-country': 'MAR', 'name': 'thematic trust funds', 'value': 0},
{'donor-country': 'MAR', 'name': 'non-core', 'value': 10762031},
{'donor-country': 'MAR', 'name': 'special activities', 'value': 0},
{'donor-country': 'ROM', 'name': 'core', 'value': 0},
{'donor-country': 'ROM', 'name': 'trust funds', 'value': 0},
{'donor-country': 'ROM', 'name': 'unv', 'value': 0},
{'donor-country': 'ROM', 'name': 'cost sharing', 'value': 1991880},
{'donor-country': 'ROM', 'name': 'thematic trust funds', 'value': 0},
{'donor-country': 'ROM', 'name': 'non-core', 'value': 1991880},
{'donor-country': 'ROM', 'name': 'special activities', 'value': 0},
{'donor-country': 'COM', 'name': 'core', 'value': 0},
{'donor-country': 'COM', 'name': 'trust funds', 'value': 0},
{'donor-country': 'COM', 'name': 'unv', 'value': 0},
{'donor-country': 'COM', 'name': 'cost sharing', 'value': 0},
{'donor-country': 'COM', 'name': 'thematic trust funds', 'value': 0},
{'donor-country': 'COM', 'name': 'non-core', 'value': 0},
{'donor-country': 'COM', 'name': 'special activities', 'value': 0},
{'donor-country': 'TKL', 'name': 'core', 'value': 44190},
{'donor-country': 'TKL', 'name': 'trust funds', 'value': 0},
{'donor-country': 'TKL', 'name': 'unv', 'value': 0},
{'donor-country': 'TKL', 'name': 'cost sharing', 'value': 0},
{'donor-country': 'TKL', 'name': 'thematic trust funds', 'value': 0},
{'donor-country': 'TKL', 'name': 'non-core', 'value': 0},
{'donor-country': 'TKL', 'name': 'special activities', 'value': 0},
{'donor-country': 'TKM', 'name': 'core', 'value': 0},
{'donor-country': 'TKM', 'name': 'trust funds', 'value': 0},
{'donor-country': 'TKM', 'name': 'unv', 'value': 0},
{'donor-country': 'TKM', 'name': 'cost sharing', 'value': 0},
{'donor-country': 'TKM', 'name': 'thematic trust funds', 'value': 0},
{'donor-country': 'TKM', 'name': 'non-core', 'value': 0},
{'donor-country': 'TKM', 'name': 'special activities', 'value': 0},
{'donor-country': 'TTO', 'name': 'core', 'value': 0},
{'donor-country': 'TTO', 'name': 'trust funds', 'value': 2000},
{'donor-country': 'TTO', 'name': 'unv', 'value': 0},
{'donor-country': 'TTO', 'name': 'cost sharing', 'value': 329509},
{'donor-country': 'TTO', 'name': 'thematic trust funds', 'value': 0},
{'donor-country': 'TTO', 'name': 'non-core', 'value': 331509},
{'donor-country': 'TTO', 'name': 'special activities', 'value': 0},
{'donor-country': 'NLD', 'name': 'core', 'value': 0},
{'donor-country': 'NLD', 'name': 'trust funds', 'value': 359965},
{'donor-country': 'NLD', 'name': 'unv', 'value': 0},
{'donor-country': 'NLD', 'name': 'cost sharing', 'value': 22763637},
{'donor-country': 'NLD', 'name': 'thematic trust funds', 'value': 34817},
{'donor-country': 'NLD', 'name': 'non-core', 'value': 23158419},
{'donor-country': 'NLD', 'name': 'special activities', 'value': 0},
{'donor-country': 'BMU', 'name': 'core', 'value': 0},
{'donor-country': 'BMU', 'name': 'trust funds', 'value': 0},
{'donor-country': 'BMU', 'name': 'unv', 'value': 0},
{'donor-country': 'BMU', 'name': 'cost sharing', 'value': 0},
{'donor-country': 'BMU', 'name': 'thematic trust funds', 'value': 0},
{'donor-country': 'BMU', 'name': 'non-core', 'value': 0},
{'donor-country': 'BMU', 'name': 'special activities', 'value': 0},
{'donor-country': 'TCD', 'name': 'core', 'value': 0},
{'donor-country': 'TCD', 'name': 'trust funds', 'value': 0},
{'donor-country': 'TCD', 'name': 'unv', 'value': 0},
{'donor-country': 'TCD', 'name': 'cost sharing', 'value': 258564},
{'donor-country': 'TCD', 'name': 'thematic trust funds', 'value': 0},
{'donor-country': 'TCD', 'name': 'non-core', 'value': 258564},
{'donor-country': 'TCD', 'name': 'special activities', 'value': 0},
{'donor-country': 'GEO', 'name': 'core', 'value': 0},
{'donor-country': 'GEO', 'name': 'trust funds', 'value': 0},
{'donor-country': 'GEO', 'name': 'unv', 'value': 0},
{'donor-country': 'GEO', 'name': 'cost sharing', 'value': 132626},
{'donor-country': 'GEO', 'name': 'thematic trust funds', 'value': 0},
{'donor-country': 'GEO', 'name': 'non-core', 'value': 132626},
{'donor-country': 'GEO', 'name': 'special activities', 'value': 0},
{'donor-country': 'MNE', 'name': 'core', 'value': 0},
{'donor-country': 'MNE', 'name': 'trust funds', 'value': 0},
{'donor-country': 'MNE', 'name': 'unv', 'value': 0},
{'donor-country': 'MNE', 'name': 'cost sharing', 'value': 512011},
{'donor-country': 'MNE', 'name': 'thematic trust funds', 'value': 0},
{'donor-country': 'MNE', 'name': 'non-core', 'value': 512011},
{'donor-country': 'MNE', 'name': 'special activities', 'value': 0},
{'donor-country': 'MNG', 'name': 'core', 'value': 59472},
{'donor-country': 'MNG', 'name': 'trust funds', 'value': 0},
{'donor-country': 'MNG', 'name': 'unv', 'value': 0},
{'donor-country': 'MNG', 'name': 'cost sharing', 'value': 50000},
{'donor-country': 'MNG', 'name': 'thematic trust funds', 'value': 0},
{'donor-country': 'MNG', 'name': 'non-core', 'value': 50000},
{'donor-country': 'MNG', 'name': 'special activities', 'value': 0},
{'donor-country': 'MHL', 'name': 'core', 'value': 0},
{'donor-country': 'MHL', 'name': 'trust funds', 'value': 0},
{'donor-country': 'MHL', 'name': 'unv', 'value': 0},
{'donor-country': 'MHL', 'name': 'cost sharing', 'value': 0},
{'donor-country': 'MHL', 'name': 'thematic trust funds', 'value': 0},
{'donor-country': 'MHL', 'name': 'non-core', 'value': 0},
{'donor-country': 'MHL', 'name': 'special activities', 'value': 0},
{'donor-country': 'BLZ', 'name': 'core', 'value': 31248},
{'donor-country': 'BLZ', 'name': 'trust funds', 'value': 0},
{'donor-country': 'BLZ', 'name': 'unv', 'value': 0},
{'donor-country': 'BLZ', 'name': 'cost sharing', 'value': 0},
{'donor-country': 'BLZ', 'name': 'thematic trust funds', 'value': 0},
{'donor-country': 'BLZ', 'name': 'non-core', 'value': 0},
{'donor-country': 'BLZ', 'name': 'special activities', 'value': 0},
{'donor-country': 'MMR', 'name': 'core', 'value': 1765},
{'donor-country': 'MMR', 'name': 'trust funds', 'value': 0},
{'donor-country': 'MMR', 'name': 'unv', 'value': 0},
{'donor-country': 'MMR', 'name': 'cost sharing', 'value': 0},
{'donor-country': 'MMR', 'name': 'thematic trust funds', 'value': 0},
{'donor-country': 'MMR', 'name': 'non-core', 'value': 0},
{'donor-country': 'MMR', 'name': 'special activities', 'value': 0},
{'donor-country': 'AFG', 'name': 'core', 'value': 0},
{'donor-country': 'AFG', 'name': 'trust funds', 'value': 0},
{'donor-country': 'AFG', 'name': 'unv', 'value': 0},
{'donor-country': 'AFG', 'name': 'cost sharing', 'value': 194476},
{'donor-country': 'AFG', 'name': 'thematic trust funds', 'value': 0},
{'donor-country': 'AFG', 'name': 'non-core', 'value': 194476},
{'donor-country': 'AFG', 'name': 'special activities', 'value': 0},
{'donor-country': 'BDI', 'name': 'core', 'value': 0},
{'donor-country': 'BDI', 'name': 'trust funds', 'value': 0},
{'donor-country': 'BDI', 'name': 'unv', 'value': 0},
{'donor-country': 'BDI', 'name': 'cost sharing', 'value': 10234},
{'donor-country': 'BDI', 'name': 'thematic trust funds', 'value': 0},
{'donor-country': 'BDI', 'name': 'non-core', 'value': 10234},
{'donor-country': 'BDI', 'name': 'special activities', 'value': 0},
{'donor-country': 'VGB', 'name': 'core', 'value': 0},
{'donor-country': 'VGB', 'name': 'trust funds', 'value': 0},
{'donor-country': 'VGB', 'name': 'unv', 'value': 0},
{'donor-country': 'VGB', 'name': 'cost sharing', 'value': 0},
{'donor-country': 'VGB', 'name': 'thematic trust funds', 'value': 0},
{'donor-country': 'VGB', 'name': 'non-core', 'value': 0},
{'donor-country': 'VGB', 'name': 'special activities', 'value': 0},
{'donor-country': 'BLR', 'name': 'core', 'value': 214279},
{'donor-country': 'BLR', 'name': 'trust funds', 'value': 0},
{'donor-country': 'BLR', 'name': 'unv', 'value': 0},
{'donor-country': 'BLR', 'name': 'cost sharing', 'value': 0},
{'donor-country': 'BLR', 'name': 'thematic trust funds', 'value': 0},
{'donor-country': 'BLR', 'name': 'non-core', 'value': 0},
{'donor-country': 'BLR', 'name': 'special activities', 'value': 0},
{'donor-country': 'GRD', 'name': 'core', 'value': 0},
{'donor-country': 'GRD', 'name': 'trust funds', 'value': 0},
{'donor-country': 'GRD', 'name': 'unv', 'value': 0},
{'donor-country': 'GRD', 'name': 'cost sharing', 'value': 0},
{'donor-country': 'GRD', 'name': 'thematic trust funds', 'value': 0},
{'donor-country': 'GRD', 'name': 'non-core', 'value': 0},
{'donor-country': 'GRD', 'name': 'special activities', 'value': 0},
{'donor-country': 'GRC', 'name': 'core', 'value': 0},
{'donor-country': 'GRC', 'name': 'trust funds', 'value': -300400},
{'donor-country': 'GRC', 'name': 'unv', 'value': 0},
{'donor-country': 'GRC', 'name': 'cost sharing', 'value': 377553},
{'donor-country': 'GRC', 'name': 'thematic trust funds', 'value': 0},
{'donor-country': 'GRC', 'name': 'non-core', 'value': 77153},
{'donor-country': 'GRC', 'name': 'special activities', 'value': 0},
{'donor-country': 'LSO', 'name': 'core', 'value': 125604},
{'donor-country': 'LSO', 'name': 'trust funds', 'value': 0},
{'donor-country': 'LSO', 'name': 'unv', 'value': 0},
{'donor-country': 'LSO', 'name': 'cost sharing', 'value': 0},
{'donor-country': 'LSO', 'name': 'thematic trust funds', 'value': 0},
{'donor-country': 'LSO', 'name': 'non-core', 'value': 0},
{'donor-country': 'LSO', 'name': 'special activities', 'value': 0},
{'donor-country': 'FUNDS_GEF', 'name': 'core', 'value': 0},
{'donor-country': 'FUNDS_GEF', 'name': 'trust funds', 'value': 0},
{'donor-country': 'FUNDS_GEF', 'name': 'unv', 'value': 0},
{'donor-country': 'FUNDS_GEF', 'name': 'cost sharing', 'value': 0},
{'donor-country': 'FUNDS_GEF', 'name': 'thematic trust funds', 'value': 0},
{'donor-country': 'FUNDS_GEF', 'name': 'non-core', 'value': 0},
{'donor-country': 'FUNDS_GEF', 'name': 'special activities', 'value': 0},
{'donor-country': 'AND', 'name': 'core', 'value': 13692},
{'donor-country': 'AND', 'name': 'trust funds', 'value': 0},
{'donor-country': 'AND', 'name': 'unv', 'value': 0},
{'donor-country': 'AND', 'name': 'cost sharing', 'value': 0},
{'donor-country': 'AND', 'name': 'thematic trust funds', 'value': 0},
{'donor-country': 'AND', 'name': 'non-core', 'value': 0},
{'donor-country': 'AND', 'name': 'special activities', 'value': 0},
{'donor-country': 'MOZ', 'name': 'core', 'value': 0},
{'donor-country': 'MOZ', 'name': 'trust funds', 'value': 0},
{'donor-country': 'MOZ', 'name': 'unv', 'value': 0},
{'donor-country': 'MOZ', 'name': 'cost sharing', 'value': 0},
{'donor-country': 'MOZ', 'name': 'thematic trust funds', 'value': 0},
{'donor-country': 'MOZ', 'name': 'non-core', 'value': 0},
{'donor-country': 'MOZ', 'name': 'special activities', 'value': 0},
{'donor-country': 'TJK', 'name': 'core', 'value': 0},
{'donor-country': 'TJK', 'name': 'trust funds', 'value': 0},
{'donor-country': 'TJK', 'name': 'unv', 'value': 0},
{'donor-country': 'TJK', 'name': 'cost sharing', 'value': 0},
{'donor-country': 'TJK', 'name': 'thematic trust funds', 'value': 0},
{'donor-country': 'TJK', 'name': 'non-core', 'value': 0},
{'donor-country': 'TJK', 'name': 'special activities', 'value': 0},
{'donor-country': 'HTI', 'name': 'core', 'value': 0},
{'donor-country': 'HTI', 'name': 'trust funds', 'value': 0},
{'donor-country': 'HTI', 'name': 'unv', 'value': 0},
{'donor-country': 'HTI', 'name': 'cost sharing', 'value': 0},
{'donor-country': 'HTI', 'name': 'thematic trust funds', 'value': 0},
{'donor-country': 'HTI', 'name': 'non-core', 'value': 0},
{'donor-country': 'HTI', 'name': 'special activities', 'value': 0},
{'donor-country': 'PSE', 'name': 'core', 'value': 0},
{'donor-country': 'PSE', 'name': 'trust funds', 'value': 0},
{'donor-country': 'PSE', 'name': 'unv', 'value': 0},
{'donor-country': 'PSE', 'name': 'cost sharing', 'value': 1039259},
{'donor-country': 'PSE', 'name': 'thematic trust funds', 'value': 0},
{'donor-country': 'PSE', 'name': 'non-core', 'value': 1039259},
{'donor-country': 'PSE', 'name': 'special activities', 'value': 0},
{'donor-country': 'ANT', 'name': 'core', 'value': 0},
{'donor-country': 'ANT', 'name': 'trust funds', 'value': 6000},
{'donor-country': 'ANT', 'name': 'unv', 'value': 0},
{'donor-country': 'ANT', 'name': 'cost sharing', 'value': -283},
{'donor-country': 'ANT', 'name': 'thematic trust funds', 'value': 0},
{'donor-country': 'ANT', 'name': 'non-core', 'value': 5717},
{'donor-country': 'ANT', 'name': 'special activities', 'value': 0},
{'donor-country': 'ZWE', 'name': 'core', 'value': 0},
{'donor-country': 'ZWE', 'name': 'trust funds', 'value': 0},
{'donor-country': 'ZWE', 'name': 'unv', 'value': 0},
{'donor-country': 'ZWE', 'name': 'cost sharing', 'value': -5605},
{'donor-country': 'ZWE', 'name': 'thematic trust funds', 'value': 0},
{'donor-country': 'ZWE', 'name': 'non-core', 'value': -5605},
{'donor-country': 'ZWE', 'name': 'special activities', 'value': 0},
{'donor-country': 'LCA', 'name': 'core', 'value': 0},
{'donor-country': 'LCA', 'name': 'trust funds', 'value': 0},
{'donor-country': 'LCA', 'name': 'unv', 'value': 0},
{'donor-country': 'LCA', 'name': 'cost sharing', 'value': 0},
{'donor-country': 'LCA', 'name': 'thematic trust funds', 'value': 0},
{'donor-country': 'LCA', 'name': 'non-core', 'value': 0},
{'donor-country': 'LCA', 'name': 'special activities', 'value': 0},
{'donor-country': 'IND', 'name': 'core', 'value': 4669929},
{'donor-country': 'IND', 'name': 'trust funds', 'value': 2360000},
{'donor-country': 'IND', 'name': 'unv', 'value': 0},
{'donor-country': 'IND', 'name': 'cost sharing', 'value': 13873089},
{'donor-country': 'IND', 'name': 'thematic trust funds', 'value': 0},
{'donor-country': 'IND', 'name': 'non-core', 'value': 16233089},
{'donor-country': 'IND', 'name': 'special activities', 'value': 0},
{'donor-country': 'LVA', 'name': 'core', 'value': 0},
{'donor-country': 'LVA', 'name': 'trust funds', 'value': -15239},
{'donor-country': 'LVA', 'name': 'unv', 'value': 0},
{'donor-country': 'LVA', 'name': 'cost sharing', 'value': 0},
{'donor-country': 'LVA', 'name': 'thematic trust funds', 'value': 0},
{'donor-country': 'LVA', 'name': 'non-core', 'value': -15239},
{'donor-country': 'LVA', 'name': 'special activities', 'value': 0},
{'donor-country': 'BTN', 'name': 'core', 'value': 106724},
{'donor-country': 'BTN', 'name': 'trust funds', 'value': 0},
{'donor-country': 'BTN', 'name': 'unv', 'value': 3948},
{'donor-country': 'BTN', 'name': 'cost sharing', 'value': 0},
{'donor-country': 'BTN', 'name': 'thematic trust funds', 'value': 0},
{'donor-country': 'BTN', 'name': 'non-core', 'value': 3948},
{'donor-country': 'BTN', 'name': 'special activities', 'value': 0},
{'donor-country': 'VCT', 'name': 'core', 'value': 0},
{'donor-country': 'VCT', 'name': 'trust funds', 'value': 0},
{'donor-country': 'VCT', 'name': 'unv', 'value': 0},
{'donor-country': 'VCT', 'name': 'cost sharing', 'value': 0},
{'donor-country': 'VCT', 'name': 'thematic trust funds', 'value': 0},
{'donor-country': 'VCT', 'name': 'non-core', 'value': 0},
{'donor-country': 'VCT', 'name': 'special activities', 'value': 0},
{'donor-country': 'PRIV_INTL 1', 'name': 'core', 'value': 0},
{'donor-country': 'PRIV_INTL 1', 'name': 'trust funds', 'value': -907397},
{'donor-country': 'PRIV_INTL 1', 'name': 'unv', 'value': 25},
{'donor-country': 'PRIV_INTL 1', 'name': 'cost sharing', 'value': 31477487},
{'donor-country': 'PRIV_INTL 1', 'name': 'thematic trust funds', 'value': 105000},
{'donor-country': 'PRIV_INTL 1', 'name': 'non-core', 'value': 30675115},
{'donor-country': 'PRIV_INTL 1', 'name': 'special activities', 'value': 0},
{'donor-country': 'NOR', 'name': 'core', 'value': 112211221},
{'donor-country': 'NOR', 'name': 'trust funds', 'value': 732125},
{'donor-country': 'NOR', 'name': 'unv', 'value': 0},
{'donor-country': 'NOR', 'name': 'cost sharing', 'value': 51957482},
{'donor-country': 'NOR', 'name': 'thematic trust funds', 'value': 14106491},
{'donor-country': 'NOR', 'name': 'non-core', 'value': 72026313},
{'donor-country': 'NOR', 'name': 'special activities', 'value': 5230215},
{'donor-country': 'CZE', 'name': 'core', 'value': 0},
{'donor-country': 'CZE', 'name': 'trust funds', 'value': 10064},
{'donor-country': 'CZE', 'name': 'unv', 'value': 264302},
{'donor-country': 'CZE', 'name': 'cost sharing', 'value': 510673},
{'donor-country': 'CZE', 'name': 'thematic trust funds', 'value': 0},
{'donor-country': 'CZE', 'name': 'non-core', 'value': 785039},
{'donor-country': 'CZE', 'name': 'special activities', 'value': 0},
{'donor-country': 'FJI', 'name': 'core', 'value': 0},
{'donor-country': 'FJI', 'name': 'trust funds', 'value': 10000},
{'donor-country': 'FJI', 'name': 'unv', 'value': 0},
{'donor-country': 'FJI', 'name': 'cost sharing', 'value': 0},
{'donor-country': 'FJI', 'name': 'thematic trust funds', 'value': 0},
{'donor-country': 'FJI', 'name': 'non-core', 'value': 10000},
{'donor-country': 'FJI', 'name': 'special activities', 'value': 0},
{'donor-country': 'HND', 'name': 'core', 'value': 0},
{'donor-country': 'HND', 'name': 'trust funds', 'value': 0},
{'donor-country': 'HND', 'name': 'unv', 'value': 0},
{'donor-country': 'HND', 'name': 'cost sharing', 'value': 7571500},
{'donor-country': 'HND', 'name': 'thematic trust funds', 'value': 0},
{'donor-country': 'HND', 'name': 'non-core', 'value': 7571500},
{'donor-country': 'HND', 'name': 'special activities', 'value': 0},
{'donor-country': 'AGO', 'name': 'core', 'value': 1757426},
{'donor-country': 'AGO', 'name': 'trust funds', 'value': 0},
{'donor-country': 'AGO', 'name': 'unv', 'value': 0},
{'donor-country': 'AGO', 'name': 'cost sharing', 'value': -326},
{'donor-country': 'AGO', 'name': 'thematic trust funds', 'value': 0},
{'donor-country': 'AGO', 'name': 'non-core', 'value': -326},
{'donor-country': 'AGO', 'name': 'special activities', 'value': 0},
{'donor-country': 'DOM', 'name': 'core', 'value': 0},
{'donor-country': 'DOM', 'name': 'trust funds', 'value': 0},
{'donor-country': 'DOM', 'name': 'unv', 'value': 0},
{'donor-country': 'DOM', 'name': 'cost sharing', 'value': 5863305},
{'donor-country': 'DOM', 'name': 'thematic trust funds', 'value': 0},
{'donor-country': 'DOM', 'name': 'non-core', 'value': 5863305},
{'donor-country': 'DOM', 'name': 'special activities', 'value': 0},
{'donor-country': 'LUX', 'name': 'core', 'value': 3605442},
{'donor-country': 'LUX', 'name': 'trust funds', 'value': 191571},
{'donor-country': 'LUX', 'name': 'unv', 'value': 0},
{'donor-country': 'LUX', 'name': 'cost sharing', 'value': 5045999},
{'donor-country': 'LUX', 'name': 'thematic trust funds', 'value': 3867029},
{'donor-country': 'LUX', 'name': 'non-core', 'value': 9104599},
{'donor-country': 'LUX', 'name': 'special activities', 'value': 0},
{'donor-country': 'ISR', 'name': 'core', 'value': 0},
{'donor-country': 'ISR', 'name': 'trust funds', 'value': 0},
{'donor-country': 'ISR', 'name': 'unv', 'value': 0},
{'donor-country': 'ISR', 'name': 'cost sharing', 'value': -346},
{'donor-country': 'ISR', 'name': 'thematic trust funds', 'value': 0},
{'donor-country': 'ISR', 'name': 'non-core', 'value': -346},
{'donor-country': 'ISR', 'name': 'special activities', 'value': 0},
{'donor-country': 'FSM', 'name': 'core', 'value': 30000},
{'donor-country': 'FSM', 'name': 'trust funds', 'value': 0},
{'donor-country': 'FSM', 'name': 'unv', 'value': 0},
{'donor-country': 'FSM', 'name': 'cost sharing', 'value': 0},
{'donor-country': 'FSM', 'name': 'thematic trust funds', 'value': 0},
{'donor-country': 'FSM', 'name': 'non-core', 'value': 0},
{'donor-country': 'FSM', 'name': 'special activities', 'value': 0},
{'donor-country': 'PER', 'name': 'core', 'value': 724752},
{'donor-country': 'PER', 'name': 'trust funds', 'value': 20000},
{'donor-country': 'PER', 'name': 'unv', 'value': 0},
{'donor-country': 'PER', 'name': 'cost sharing', 'value': 28983570},
{'donor-country': 'PER', 'name': 'thematic trust funds', 'value': 0},
{'donor-country': 'PER', 'name': 'non-core', 'value': 29003570},
{'donor-country': 'PER', 'name': 'special activities', 'value': 0},
{'donor-country': 'REU', 'name': 'core', 'value': 0},
{'donor-country': 'REU', 'name': 'trust funds', 'value': 0},
{'donor-country': 'REU', 'name': 'unv', 'value': 0},
{'donor-country': 'REU', 'name': 'cost sharing', 'value': 0},
{'donor-country': 'REU', 'name': 'thematic trust funds', 'value': 0},
{'donor-country': 'REU', 'name': 'non-core', 'value': 0},
{'donor-country': 'REU', 'name': 'special activities', 'value': 0},
{'donor-country': 'IDN', 'name': 'core', 'value': 0},
{'donor-country': 'IDN', 'name': 'trust funds', 'value': 7000},
{'donor-country': 'IDN', 'name': 'unv', 'value': 0},
{'donor-country': 'IDN', 'name': 'cost sharing', 'value': 0},
{'donor-country': 'IDN', 'name': 'thematic trust funds', 'value': 0},
{'donor-country': 'IDN', 'name': 'non-core', 'value': 7000},
{'donor-country': 'IDN', 'name': 'special activities', 'value': 0},
{'donor-country': 'MKD', 'name': 'core', 'value': 0},
{'donor-country': 'MKD', 'name': 'trust funds', 'value': 0},
{'donor-country': 'MKD', 'name': 'unv', 'value': 0},
{'donor-country': 'MKD', 'name': 'cost sharing', 'value': 2659590},
{'donor-country': 'MKD', 'name': 'thematic trust funds', 'value': 0},
{'donor-country': 'MKD', 'name': 'non-core', 'value': 2659590},
{'donor-country': 'MKD', 'name': 'special activities', 'value': 0},
{'donor-country': 'SUR', 'name': 'core', 'value': 0},
{'donor-country': 'SUR', 'name': 'trust funds', 'value': 0},
{'donor-country': 'SUR', 'name': 'unv', 'value': 0},
{'donor-country': 'SUR', 'name': 'cost sharing', 'value': 0},
{'donor-country': 'SUR', 'name': 'thematic trust funds', 'value': 0},
{'donor-country': 'SUR', 'name': 'non-core', 'value': 0},
{'donor-country': 'SUR', 'name': 'special activities', 'value': 0},
{'donor-country': 'COG', 'name': 'core', 'value': 0},
{'donor-country': 'COG', 'name': 'trust funds', 'value': 0},
{'donor-country': 'COG', 'name': 'unv', 'value': 0},
{'donor-country': 'COG', 'name': 'cost sharing', 'value': 5676484},
{'donor-country': 'COG', 'name': 'thematic trust funds', 'value': 0},
{'donor-country': 'COG', 'name': 'non-core', 'value': 5676484},
{'donor-country': 'COG', 'name': 'special activities', 'value': 0},
{'donor-country': 'ISL', 'name': 'core', 'value': 0},
{'donor-country': 'ISL', 'name': 'trust funds', 'value': 0},
{'donor-country': 'ISL', 'name': 'unv', 'value': 0},
{'donor-country': 'ISL', 'name': 'cost sharing', 'value': 0},
{'donor-country': 'ISL', 'name': 'thematic trust funds', 'value': 0},
{'donor-country': 'ISL', 'name': 'non-core', 'value': 0},
{'donor-country': 'ISL', 'name': 'special activities', 'value': 0},
{'donor-country': 'ETH', 'name': 'core', 'value': 0},
{'donor-country': 'ETH', 'name': 'trust funds', 'value': 0},
{'donor-country': 'ETH', 'name': 'unv', 'value': 0},
{'donor-country': 'ETH', 'name': 'cost sharing', 'value': 0},
{'donor-country': 'ETH', 'name': 'thematic trust funds', 'value': 0},
{'donor-country': 'ETH', 'name': 'non-core', 'value': 0},
{'donor-country': 'ETH', 'name': 'special activities', 'value': 0},
{'donor-country': 'NER', 'name': 'core', 'value': 0},
{'donor-country': 'NER', 'name': 'trust funds', 'value': 0},
{'donor-country': 'NER', 'name': 'unv', 'value': 0},
{'donor-country': 'NER', 'name': 'cost sharing', 'value': 0},
{'donor-country': 'NER', 'name': 'thematic trust funds', 'value': 0},
{'donor-country': 'NER', 'name': 'non-core', 'value': 0},
{'donor-country': 'NER', 'name': 'special activities', 'value': 0},
{'donor-country': 'COL', 'name': 'core', 'value': 0},
{'donor-country': 'COL', 'name': 'trust funds', 'value': 0},
{'donor-country': 'COL', 'name': 'unv', 'value': 0},
{'donor-country': 'COL', 'name': 'cost sharing', 'value': 29638534},
{'donor-country': 'COL', 'name': 'thematic trust funds', 'value': 0},
{'donor-country': 'COL', 'name': 'non-core', 'value': 29638534},
{'donor-country': 'COL', 'name': 'special activities', 'value': 0},
{'donor-country': 'FUNDS_EU', 'name': 'core', 'value': 0},
{'donor-country': 'FUNDS_EU', 'name': 'trust funds', 'value': 0},
{'donor-country': 'FUNDS_EU', 'name': 'unv', 'value': 0},
{'donor-country': 'FUNDS_EU', 'name': 'cost sharing', 'value': 0},
{'donor-country': 'FUNDS_EU', 'name': 'thematic trust funds', 'value': 0},
{'donor-country': 'FUNDS_EU', 'name': 'non-core', 'value': 0},
{'donor-country': 'FUNDS_EU', 'name': 'special activities', 'value': 0},
{'donor-country': 'PRT', 'name': 'core', 'value': 0},
{'donor-country': 'PRT', 'name': 'trust funds', 'value': 0},
{'donor-country': 'PRT', 'name': 'unv', 'value': 0},
{'donor-country': 'PRT', 'name': 'cost sharing', 'value': 399402},
{'donor-country': 'PRT', 'name': 'thematic trust funds', 'value': 0},
{'donor-country': 'PRT', 'name': 'non-core', 'value': 399402},
{'donor-country': 'PRT', 'name': 'special activities', 'value': 0},
{'donor-country': 'MDA', 'name': 'core', 'value': 0},
{'donor-country': 'MDA', 'name': 'trust funds', 'value': 0},
{'donor-country': 'MDA', 'name': 'unv', 'value': 0},
{'donor-country': 'MDA', 'name': 'cost sharing', 'value': 0},
{'donor-country': 'MDA', 'name': 'thematic trust funds', 'value': 0},
{'donor-country': 'MDA', 'name': 'non-core', 'value': 0},
{'donor-country': 'MDA', 'name': 'special activities', 'value': 0},
{'donor-country': 'STP', 'name': 'core', 'value': 0},
{'donor-country': 'STP', 'name': 'trust funds', 'value': 0},
{'donor-country': 'STP', 'name': 'unv', 'value': 0},
{'donor-country': 'STP', 'name': 'cost sharing', 'value': 0},
{'donor-country': 'STP', 'name': 'thematic trust funds', 'value': 0},
{'donor-country': 'STP', 'name': 'non-core', 'value': 0},
{'donor-country': 'STP', 'name': 'special activities', 'value': 0},
{'donor-country': 'MDG', 'name': 'core', 'value': 0},
{'donor-country': 'MDG', 'name': 'trust funds', 'value': 0},
{'donor-country': 'MDG', 'name': 'unv', 'value': 0},
{'donor-country': 'MDG', 'name': 'cost sharing', 'value': 0},
{'donor-country': 'MDG', 'name': 'thematic trust funds', 'value': 0},
{'donor-country': 'MDG', 'name': 'non-core', 'value': 0},
{'donor-country': 'MDG', 'name': 'special activities', 'value': 0},
{'donor-country': 'ECU', 'name': 'core', 'value': 0},
{'donor-country': 'ECU', 'name': 'trust funds', 'value': 130890},
{'donor-country': 'ECU', 'name': 'unv', 'value': 0},
{'donor-country': 'ECU', 'name': 'cost sharing', 'value': 437802},
{'donor-country': 'ECU', 'name': 'thematic trust funds', 'value': 0},
{'donor-country': 'ECU', 'name': 'non-core', 'value': 568692},
{'donor-country': 'ECU', 'name': 'special activities', 'value': 0},
{'donor-country': 'SEN', 'name': 'core', 'value': 0},
{'donor-country': 'SEN', 'name': 'trust funds', 'value': 0},
{'donor-country': 'SEN', 'name': 'unv', 'value': 0},
{'donor-country': 'SEN', 'name': 'cost sharing', 'value': 0},
{'donor-country': 'SEN', 'name': 'thematic trust funds', 'value': 0},
{'donor-country': 'SEN', 'name': 'non-core', 'value': 0},
{'donor-country': 'SEN', 'name': 'special activities', 'value': 0},
{'donor-country': 'MDV', 'name': 'core', 'value': 341957},
{'donor-country': 'MDV', 'name': 'trust funds', 'value': 0},
{'donor-country': 'MDV', 'name': 'unv', 'value': 0},
{'donor-country': 'MDV', 'name': 'cost sharing', 'value': 0},
{'donor-country': 'MDV', 'name': 'thematic trust funds', 'value': 0},
{'donor-country': 'MDV', 'name': 'non-core', 'value': 0},
{'donor-country': 'MDV', 'name': 'special activities', 'value': 0},
{'donor-country': 'PMI', 'name': 'core', 'value': 0},
{'donor-country': 'PMI', 'name': 'trust funds', 'value': 0},
{'donor-country': 'PMI', 'name': 'unv', 'value': 0},
{'donor-country': 'PMI', 'name': 'cost sharing', 'value': 0},
{'donor-country': 'PMI', 'name': 'thematic trust funds', 'value': 0},
{'donor-country': 'PMI', 'name': 'non-core', 'value': 0},
{'donor-country': 'PMI', 'name': 'special activities', 'value': 0},
{'donor-country': 'TLS', 'name': 'core', 'value': 0},
{'donor-country': 'TLS', 'name': 'trust funds', 'value': 0},
{'donor-country': 'TLS', 'name': 'unv', 'value': 0},
{'donor-country': 'TLS', 'name': 'cost sharing', 'value': 0},
{'donor-country': 'TLS', 'name': 'thematic trust funds', 'value': 0},
{'donor-country': 'TLS', 'name': 'non-core', 'value': 0},
{'donor-country': 'TLS', 'name': 'special activities', 'value': 0},
{'donor-country': 'CUV', 'name': 'core', 'value': 0},
{'donor-country': 'CUV', 'name': 'trust funds', 'value': 0},
{'donor-country': 'CUV', 'name': 'unv', 'value': 0},
{'donor-country': 'CUV', 'name': 'cost sharing', 'value': 305986},
{'donor-country': 'CUV', 'name': 'thematic trust funds', 'value': 0},
{'donor-country': 'CUV', 'name': 'non-core', 'value': 305986},
{'donor-country': 'CUV', 'name': 'special activities', 'value': 0},
{'donor-country': 'FRA', 'name': 'core', 'value': 18569464},
{'donor-country': 'FRA', 'name': 'trust funds', 'value': 102038},
{'donor-country': 'FRA', 'name': 'unv', 'value': 0},
{'donor-country': 'FRA', 'name': 'cost sharing', 'value': 931624},
{'donor-country': 'FRA', 'name': 'thematic trust funds', 'value': 0},
{'donor-country': 'FRA', 'name': 'non-core', 'value': 1126500},
{'donor-country': 'FRA', 'name': 'special activities', 'value': 92838},
{'donor-country': 'LTU', 'name': 'core', 'value': 0},
{'donor-country': 'LTU', 'name': 'trust funds', 'value': 0},
{'donor-country': 'LTU', 'name': 'unv', 'value': 0},
{'donor-country': 'LTU', 'name': 'cost sharing', 'value': 341373},
{'donor-country': 'LTU', 'name': 'thematic trust funds', 'value': 0},
{'donor-country': 'LTU', 'name': 'non-core', 'value': 341373},
{'donor-country': 'LTU', 'name': 'special activities', 'value': 0},
{'donor-country': 'RWA', 'name': 'core', 'value': 0},
{'donor-country': 'RWA', 'name': 'trust funds', 'value': 0},
{'donor-country': 'RWA', 'name': 'unv', 'value': 0},
{'donor-country': 'RWA', 'name': 'cost sharing', 'value': 0},
{'donor-country': 'RWA', 'name': 'thematic trust funds', 'value': 0},
{'donor-country': 'RWA', 'name': 'non-core', 'value': 0},
{'donor-country': 'RWA', 'name': 'special activities', 'value': 0},
{'donor-country': 'GMB', 'name': 'core', 'value': 27711},
{'donor-country': 'GMB', 'name': 'trust funds', 'value': 0},
{'donor-country': 'GMB', 'name': 'unv', 'value': 0},
{'donor-country': 'GMB', 'name': 'cost sharing', 'value': 0},
{'donor-country': 'GMB', 'name': 'thematic trust funds', 'value': 0},
{'donor-country': 'GMB', 'name': 'non-core', 'value': 0},
{'donor-country': 'GMB', 'name': 'special activities', 'value': 0},
{'donor-country': 'GTM', 'name': 'core', 'value': 0},
{'donor-country': 'GTM', 'name': 'trust funds', 'value': 0},
{'donor-country': 'GTM', 'name': 'unv', 'value': 0},
{'donor-country': 'GTM', 'name': 'cost sharing', 'value': 6326375},
{'donor-country': 'GTM', 'name': 'thematic trust funds', 'value': 0},
{'donor-country': 'GTM', 'name': 'non-core', 'value': 6326375},
{'donor-country': 'GTM', 'name': 'special activities', 'value': 0},
{'donor-country': 'DNK', 'name': 'core', 'value': 60142154},
{'donor-country': 'DNK', 'name': 'trust funds', 'value': 4362843},
{'donor-country': 'DNK', 'name': 'unv', 'value': 0},
{'donor-country': 'DNK', 'name': 'cost sharing', 'value': 18397788},
{'donor-country': 'DNK', 'name': 'thematic trust funds', 'value': 343046},
{'donor-country': 'DNK', 'name': 'non-core', 'value': 23103677},
{'donor-country': 'DNK', 'name': 'special activities', 'value': 0},
{'donor-country': 'MSR', 'name': 'core', 'value': 0},
{'donor-country': 'MSR', 'name': 'trust funds', 'value': 0},
{'donor-country': 'MSR', 'name': 'unv', 'value': 0},
{'donor-country': 'MSR', 'name': 'cost sharing', 'value': 0},
{'donor-country': 'MSR', 'name': 'thematic trust funds', 'value': 0},
{'donor-country': 'MSR', 'name': 'non-core', 'value': 0},
{'donor-country': 'MSR', 'name': 'special activities', 'value': 0},
{'donor-country': 'AUS', 'name': 'core', 'value': 18154657},
{'donor-country': 'AUS', 'name': 'trust funds', 'value': 4679099},
{'donor-country': 'AUS', 'name': 'unv', 'value': 0},
{'donor-country': 'AUS', 'name': 'cost sharing', 'value': 53549381},
{'donor-country': 'AUS', 'name': 'thematic trust funds', 'value': 3189844},
{'donor-country': 'AUS', 'name': 'non-core', 'value': 62044528},
{'donor-country': 'AUS', 'name': 'special activities', 'value': 626204},
{'donor-country': 'AUT', 'name': 'core', 'value': 2149660},
{'donor-country': 'AUT', 'name': 'trust funds', 'value': 0},
{'donor-country': 'AUT', 'name': 'unv', 'value': 0},
{'donor-country': 'AUT', 'name': 'cost sharing', 'value': 3515602},
{'donor-country': 'AUT', 'name': 'thematic trust funds', 'value': 0},
{'donor-country': 'AUT', 'name': 'non-core', 'value': 3515602},
{'donor-country': 'AUT', 'name': 'special activities', 'value': 0},
{'donor-country': 'VEN', 'name': 'core', 'value': 1195873},
{'donor-country': 'VEN', 'name': 'trust funds', 'value': 0},
{'donor-country': 'VEN', 'name': 'unv', 'value': 0},
{'donor-country': 'VEN', 'name': 'cost sharing', 'value': 15458077},
{'donor-country': 'VEN', 'name': 'thematic trust funds', 'value': 0},
{'donor-country': 'VEN', 'name': 'non-core', 'value': 15458077},
{'donor-country': 'VEN', 'name': 'special activities', 'value': 0},
{'donor-country': 'PLW', 'name': 'core', 'value': 0},
{'donor-country': 'PLW', 'name': 'trust funds', 'value': 0},
{'donor-country': 'PLW', 'name': 'unv', 'value': 0},
{'donor-country': 'PLW', 'name': 'cost sharing', 'value': 0},
{'donor-country': 'PLW', 'name': 'thematic trust funds', 'value': 0},
{'donor-country': 'PLW', 'name': 'non-core', 'value': 0},
{'donor-country': 'PLW', 'name': 'special activities', 'value': 0},
{'donor-country': 'KEN', 'name': 'core', 'value': 0},
{'donor-country': 'KEN', 'name': 'trust funds', 'value': 0},
{'donor-country': 'KEN', 'name': 'unv', 'value': 0},
{'donor-country': 'KEN', 'name': 'cost sharing', 'value': 0},
{'donor-country': 'KEN', 'name': 'thematic trust funds', 'value': 0},
{'donor-country': 'KEN', 'name': 'non-core', 'value': 0},
{'donor-country': 'KEN', 'name': 'special activities', 'value': 0},
{'donor-country': 'BRB', 'name': 'core', 'value': 0},
{'donor-country': 'BRB', 'name': 'trust funds', 'value': 0},
{'donor-country': 'BRB', 'name': 'unv', 'value': 0},
{'donor-country': 'BRB', 'name': 'cost sharing', 'value': 0},
{'donor-country': 'BRB', 'name': 'thematic trust funds', 'value': 0},
{'donor-country': 'BRB', 'name': 'non-core', 'value': 0},
{'donor-country': 'BRB', 'name': 'special activities', 'value': 0},
{'donor-country': 'WSM', 'name': 'core', 'value': 298321},
{'donor-country': 'WSM', 'name': 'trust funds', 'value': 0},
{'donor-country': 'WSM', 'name': 'unv', 'value': 0},
{'donor-country': 'WSM', 'name': 'cost sharing', 'value': 0},
{'donor-country': 'WSM', 'name': 'thematic trust funds', 'value': 0},
{'donor-country': 'WSM', 'name': 'non-core', 'value': 0},
{'donor-country': 'WSM', 'name': 'special activities', 'value': 0},
{'donor-country': 'TUR', 'name': 'core', 'value': 0},
{'donor-country': 'TUR', 'name': 'trust funds', 'value': 11820},
{'donor-country': 'TUR', 'name': 'unv', 'value': 0},
{'donor-country': 'TUR', 'name': 'cost sharing', 'value': 7090261},
{'donor-country': 'TUR', 'name': 'thematic trust funds', 'value': 0},
{'donor-country': 'TUR', 'name': 'non-core', 'value': 7102081},
{'donor-country': 'TUR', 'name': 'special activities', 'value': 0},
{'donor-country': 'ALB', 'name': 'core', 'value': 402252},
{'donor-country': 'ALB', 'name': 'trust funds', 'value': 0},
{'donor-country': 'ALB', 'name': 'unv', 'value': 0},
{'donor-country': 'ALB', 'name': 'cost sharing', 'value': 0},
{'donor-country': 'ALB', 'name': 'thematic trust funds', 'value': 0},
{'donor-country': 'ALB', 'name': 'non-core', 'value': 0},
{'donor-country': 'ALB', 'name': 'special activities', 'value': 0},
{'donor-country': 'OMN', 'name': 'core', 'value': 0},
{'donor-country': 'OMN', 'name': 'trust funds', 'value': 0},
{'donor-country': 'OMN', 'name': 'unv', 'value': 0},
{'donor-country': 'OMN', 'name': 'cost sharing', 'value': 0},
{'donor-country': 'OMN', 'name': 'thematic trust funds', 'value': 0},
{'donor-country': 'OMN', 'name': 'non-core', 'value': 0},
{'donor-country': 'OMN', 'name': 'special activities', 'value': 0},
{'donor-country': 'TUV', 'name': 'core', 'value': 0},
{'donor-country': 'TUV', 'name': 'trust funds', 'value': 0},
{'donor-country': 'TUV', 'name': 'unv', 'value': 0},
{'donor-country': 'TUV', 'name': 'cost sharing', 'value': 0},
{'donor-country': 'TUV', 'name': 'thematic trust funds', 'value': 0},
{'donor-country': 'TUV', 'name': 'non-core', 'value': 0},
{'donor-country': 'TUV', 'name': 'special activities', 'value': 0},
{'donor-country': 'ITA', 'name': 'core', 'value': 0},
{'donor-country': 'ITA', 'name': 'trust funds', 'value': -9462},
{'donor-country': 'ITA', 'name': 'unv', 'value': 651831},
{'donor-country': 'ITA', 'name': 'cost sharing', 'value': 1761437},
{'donor-country': 'ITA', 'name': 'thematic trust funds', 'value': -41258},
{'donor-country': 'ITA', 'name': 'non-core', 'value': 2362548},
{'donor-country': 'ITA', 'name': 'special activities', 'value': 0},
{'donor-country': 'BRN', 'name': 'core', 'value': 0},
{'donor-country': 'BRN', 'name': 'trust funds', 'value': 0},
{'donor-country': 'BRN', 'name': 'unv', 'value': 0},
{'donor-country': 'BRN', 'name': 'cost sharing', 'value': 0},
{'donor-country': 'BRN', 'name': 'thematic trust funds', 'value': 0},
{'donor-country': 'BRN', 'name': 'non-core', 'value': 0},
{'donor-country': 'BRN', 'name': 'special activities', 'value': 0},
{'donor-country': 'TUN', 'name': 'core', 'value': 142596},
{'donor-country': 'TUN', 'name': 'trust funds', 'value': 0},
{'donor-country': 'TUN', 'name': 'unv', 'value': 0},
{'donor-country': 'TUN', 'name': 'cost sharing', 'value': 244064},
{'donor-country': 'TUN', 'name': 'thematic trust funds', 'value': 0},
{'donor-country': 'TUN', 'name': 'non-core', 'value': 244064},
{'donor-country': 'TUN', 'name': 'special activities', 'value': 0},
{'donor-country': 'RUS', 'name': 'core', 'value': 0},
{'donor-country': 'RUS', 'name': 'trust funds', 'value': 0},
{'donor-country': 'RUS', 'name': 'unv', 'value': 0},
{'donor-country': 'RUS', 'name': 'cost sharing', 'value': 1464955},
{'donor-country': 'RUS', 'name': 'thematic trust funds', 'value': 0},
{'donor-country': 'RUS', 'name': 'non-core', 'value': 1464955},
{'donor-country': 'RUS', 'name': 'special activities', 'value': 0},
{'donor-country': 'MEX', 'name': 'core', 'value': 0},
{'donor-country': 'MEX', 'name': 'trust funds', 'value': 0},
{'donor-country': 'MEX', 'name': 'unv', 'value': 0},
{'donor-country': 'MEX', 'name': 'cost sharing', 'value': 7065491},
{'donor-country': 'MEX', 'name': 'thematic trust funds', 'value': 0},
{'donor-country': 'MEX', 'name': 'non-core', 'value': 7065491},
{'donor-country': 'MEX', 'name': 'special activities', 'value': 0},
{'donor-country': 'BRA', 'name': 'core', 'value': 0},
{'donor-country': 'BRA', 'name': 'trust funds', 'value': 0},
{'donor-country': 'BRA', 'name': 'unv', 'value': 0},
{'donor-country': 'BRA', 'name': 'cost sharing', 'value': 75427935},
{'donor-country': 'BRA', 'name': 'thematic trust funds', 'value': 0},
{'donor-country': 'BRA', 'name': 'non-core', 'value': 75427935},
{'donor-country': 'BRA', 'name': 'special activities', 'value': 0},
{'donor-country': 'CIV', 'name': 'core', 'value': 0},
{'donor-country': 'CIV', 'name': 'trust funds', 'value': 0},
{'donor-country': 'CIV', 'name': 'unv', 'value': 0},
{'donor-country': 'CIV', 'name': 'cost sharing', 'value': 1929187},
{'donor-country': 'CIV', 'name': 'thematic trust funds', 'value': 0},
{'donor-country': 'CIV', 'name': 'non-core', 'value': 1929187},
{'donor-country': 'CIV', 'name': 'special activities', 'value': 0},
{'donor-country': 'SRB', 'name': 'core', 'value': 0},
{'donor-country': 'SRB', 'name': 'trust funds', 'value': 0},
{'donor-country': 'SRB', 'name': 'unv', 'value': 0},
{'donor-country': 'SRB', 'name': 'cost sharing', 'value': 509341},
{'donor-country': 'SRB', 'name': 'thematic trust funds', 'value': 0},
{'donor-country': 'SRB', 'name': 'non-core', 'value': 509341},
{'donor-country': 'SRB', 'name': 'special activities', 'value': 0},
{'donor-country': 'GNQ', 'name': 'core', 'value': 0},
{'donor-country': 'GNQ', 'name': 'trust funds', 'value': 0},
{'donor-country': 'GNQ', 'name': 'unv', 'value': 0},
{'donor-country': 'GNQ', 'name': 'cost sharing', 'value': -2720},
{'donor-country': 'GNQ', 'name': 'thematic trust funds', 'value': 0},
{'donor-country': 'GNQ', 'name': 'non-core', 'value': -2720},
{'donor-country': 'GNQ', 'name': 'special activities', 'value': 0},
{'donor-country': 'USA', 'name': 'core', 'value': 0},
{'donor-country': 'USA', 'name': 'trust funds', 'value': 92924519},
{'donor-country': 'USA', 'name': 'unv', 'value': 0},
{'donor-country': 'USA', 'name': 'cost sharing', 'value': 94114181},
{'donor-country': 'USA', 'name': 'thematic trust funds', 'value': 2908006},
{'donor-country': 'USA', 'name': 'non-core', 'value': 194288096},
{'donor-country': 'USA', 'name': 'special activities', 'value': 4341390},
{'donor-country': 'SWE', 'name': 'core', 'value': 0},
{'donor-country': 'SWE', 'name': 'trust funds', 'value': 3995680},
{'donor-country': 'SWE', 'name': 'unv', 'value': 587813},
{'donor-country': 'SWE', 'name': 'cost sharing', 'value': 44728055},
{'donor-country': 'SWE', 'name': 'thematic trust funds', 'value': 84042},
{'donor-country': 'SWE', 'name': 'non-core', 'value': 49395590},
{'donor-country': 'SWE', 'name': 'special activities', 'value': 0},
{'donor-country': 'AZE', 'name': 'core', 'value': 0},
{'donor-country': 'AZE', 'name': 'trust funds', 'value': 0},
{'donor-country': 'AZE', 'name': 'unv', 'value': 0},
{'donor-country': 'AZE', 'name': 'cost sharing', 'value': 2062038},
{'donor-country': 'AZE', 'name': 'thematic trust funds', 'value': 0},
{'donor-country': 'AZE', 'name': 'non-core', 'value': 2062038},
{'donor-country': 'AZE', 'name': 'special activities', 'value': 0},
{'donor-country': 'GNB', 'name': 'core', 'value': 0},
{'donor-country': 'GNB', 'name': 'trust funds', 'value': 0},
{'donor-country': 'GNB', 'name': 'unv', 'value': 0},
{'donor-country': 'GNB', 'name': 'cost sharing', 'value': 172740},
{'donor-country': 'GNB', 'name': 'thematic trust funds', 'value': 0},
{'donor-country': 'GNB', 'name': 'non-core', 'value': 172740},
{'donor-country': 'GNB', 'name': 'special activities', 'value': 0},
{'donor-country': 'SWZ', 'name': 'core', 'value': 115365},
{'donor-country': 'SWZ', 'name': 'trust funds', 'value': 0},
{'donor-country': 'SWZ', 'name': 'unv', 'value': 0},
{'donor-country': 'SWZ', 'name': 'cost sharing', 'value': 329012},
{'donor-country': 'SWZ', 'name': 'thematic trust funds', 'value': 0},
{'donor-country': 'SWZ', 'name': 'non-core', 'value': 329012},
{'donor-country': 'SWZ', 'name': 'special activities', 'value': 0},
{'donor-country': 'TON', 'name': 'core', 'value': 25828},
{'donor-country': 'TON', 'name': 'trust funds', 'value': 0},
{'donor-country': 'TON', 'name': 'unv', 'value': 0},
{'donor-country': 'TON', 'name': 'cost sharing', 'value': 0},
{'donor-country': 'TON', 'name': 'thematic trust funds', 'value': 0},
{'donor-country': 'TON', 'name': 'non-core', 'value': 0},
{'donor-country': 'TON', 'name': 'special activities', 'value': 0},
{'donor-country': 'CAN', 'name': 'core', 'value': 0},
{'donor-country': 'CAN', 'name': 'trust funds', 'value': 17652544},
{'donor-country': 'CAN', 'name': 'unv', 'value': 0},
{'donor-country': 'CAN', 'name': 'cost sharing', 'value': 14546972},
{'donor-country': 'CAN', 'name': 'thematic trust funds', 'value': 0},
{'donor-country': 'CAN', 'name': 'non-core', 'value': 32476512},
{'donor-country': 'CAN', 'name': 'special activities', 'value': 276996},
{'donor-country': 'UKR', 'name': 'core', 'value': 0},
{'donor-country': 'UKR', 'name': 'trust funds', 'value': 0},
{'donor-country': 'UKR', 'name': 'unv', 'value': 0},
{'donor-country': 'UKR', 'name': 'cost sharing', 'value': 11467},
{'donor-country': 'UKR', 'name': 'thematic trust funds', 'value': 0},
{'donor-country': 'UKR', 'name': 'non-core', 'value': 11467},
{'donor-country': 'UKR', 'name': 'special activities', 'value': 0},
{'donor-country': 'KOS', 'name': 'core', 'value': 0},
{'donor-country': 'KOS', 'name': 'trust funds', 'value': 0},
{'donor-country': 'KOS', 'name': 'unv', 'value': 0},
{'donor-country': 'KOS', 'name': 'cost sharing', 'value': 897788},
{'donor-country': 'KOS', 'name': 'thematic trust funds', 'value': 0},
{'donor-country': 'KOS', 'name': 'non-core', 'value': 897788},
{'donor-country': 'KOS', 'name': 'special activities', 'value': 0},
{'donor-country': 'KOR', 'name': 'core', 'value': 6384000},
{'donor-country': 'KOR', 'name': 'trust funds', 'value': 297584},
{'donor-country': 'KOR', 'name': 'unv', 'value': 871000},
{'donor-country': 'KOR', 'name': 'cost sharing', 'value': 475333},
{'donor-country': 'KOR', 'name': 'thematic trust funds', 'value': 0},
{'donor-country': 'KOR', 'name': 'non-core', 'value': 1643917},
{'donor-country': 'KOR', 'name': 'special activities', 'value': 0},
{'donor-country': 'AIA', 'name': 'core', 'value': 0},
{'donor-country': 'AIA', 'name': 'trust funds', 'value': 0},
{'donor-country': 'AIA', 'name': 'unv', 'value': 0},
{'donor-country': 'AIA', 'name': 'cost sharing', 'value': 0},
{'donor-country': 'AIA', 'name': 'thematic trust funds', 'value': 0},
{'donor-country': 'AIA', 'name': 'non-core', 'value': 0},
{'donor-country': 'AIA', 'name': 'special activities', 'value': 0},
{'donor-country': 'CAF', 'name': 'core', 'value': 0},
{'donor-country': 'CAF', 'name': 'trust funds', 'value': 0},
{'donor-country': 'CAF', 'name': 'unv', 'value': 0},
{'donor-country': 'CAF', 'name': 'cost sharing', 'value': 0},
{'donor-country': 'CAF', 'name': 'thematic trust funds', 'value': 0},
{'donor-country': 'CAF', 'name': 'non-core', 'value': 0},
{'donor-country': 'CAF', 'name': 'special activities', 'value': 0},
{'donor-country': 'SVK', 'name': 'core', 'value': 0},
{'donor-country': 'SVK', 'name': 'trust funds', 'value': 0},
{'donor-country': 'SVK', 'name': 'unv', 'value': 0},
{'donor-country': 'SVK', 'name': 'cost sharing', 'value': 621315},
{'donor-country': 'SVK', 'name': 'thematic trust funds', 'value': 0},
{'donor-country': 'SVK', 'name': 'non-core', 'value': 621315},
{'donor-country': 'SVK', 'name': 'special activities', 'value': 0},
{'donor-country': 'NHE', 'name': 'core', 'value': 0},
{'donor-country': 'NHE', 'name': 'trust funds', 'value': 0},
{'donor-country': 'NHE', 'name': 'unv', 'value': 0},
{'donor-country': 'NHE', 'name': 'cost sharing', 'value': 0},
{'donor-country': 'NHE', 'name': 'thematic trust funds', 'value': 0},
{'donor-country': 'NHE', 'name': 'non-core', 'value': 0},
{'donor-country': 'NHE', 'name': 'special activities', 'value': 0},
{'donor-country': 'CYP', 'name': 'core', 'value': 0},
{'donor-country': 'CYP', 'name': 'trust funds', 'value': 0},
{'donor-country': 'CYP', 'name': 'unv', 'value': 0},
{'donor-country': 'CYP', 'name': 'cost sharing', 'value': -47276},
{'donor-country': 'CYP', 'name': 'thematic trust funds', 'value': 0},
{'donor-country': 'CYP', 'name': 'non-core', 'value': -47276},
{'donor-country': 'CYP', 'name': 'special activities', 'value': 0},
{'donor-country': 'BIH', 'name': 'core', 'value': 0},
{'donor-country': 'BIH', 'name': 'trust funds', 'value': 0},
{'donor-country': 'BIH', 'name': 'unv', 'value': 0},
{'donor-country': 'BIH', 'name': 'cost sharing', 'value': 784708},
{'donor-country': 'BIH', 'name': 'thematic trust funds', 'value': 0},
{'donor-country': 'BIH', 'name': 'non-core', 'value': 784708},
{'donor-country': 'BIH', 'name': 'special activities', 'value': 0},
{'donor-country': 'SGP', 'name': 'core', 'value': 300000},
{'donor-country': 'SGP', 'name': 'trust funds', 'value': 0},
{'donor-country': 'SGP', 'name': 'unv', 'value': 0},
{'donor-country': 'SGP', 'name': 'cost sharing', 'value': 0},
{'donor-country': 'SGP', 'name': 'thematic trust funds', 'value': 0},
{'donor-country': 'SGP', 'name': 'non-core', 'value': 0},
{'donor-country': 'SGP', 'name': 'special activities', 'value': 0},
{'donor-country': '-', 'name': 'core', 'value': -110631},
{'donor-country': '-', 'name': 'trust funds', 'value': 13557865},
{'donor-country': '-', 'name': 'unv', 'value': -6290673},
{'donor-country': '-', 'name': 'cost sharing', 'value': 4998644},
{'donor-country': '-', 'name': 'thematic trust funds', 'value': -60326},
{'donor-country': '-', 'name': 'non-core', 'value': 12273866},
{'donor-country': '-', 'name': 'special activities', 'value': 68356},
{'donor-country': 'UZB', 'name': 'core', 'value': 0},
{'donor-country': 'UZB', 'name': 'trust funds', 'value': 0},
{'donor-country': 'UZB', 'name': 'unv', 'value': 0},
{'donor-country': 'UZB', 'name': 'cost sharing', 'value': 469656},
{'donor-country': 'UZB', 'name': 'thematic trust funds', 'value': 0},
{'donor-country': 'UZB', 'name': 'non-core', 'value': 469656},
{'donor-country': 'UZB', 'name': 'special activities', 'value': 0},
{'donor-country': 'ERI', 'name': 'core', 'value': 114017},
{'donor-country': 'ERI', 'name': 'trust funds', 'value': 0},
{'donor-country': 'ERI', 'name': 'unv', 'value': 0},
{'donor-country': 'ERI', 'name': 'cost sharing', 'value': 0},
{'donor-country': 'ERI', 'name': 'thematic trust funds', 'value': 0},
{'donor-country': 'ERI', 'name': 'non-core', 'value': 0},
{'donor-country': 'ERI', 'name': 'special activities', 'value': 0},
{'donor-country': 'POL', 'name': 'core', 'value': 0},
{'donor-country': 'POL', 'name': 'trust funds', 'value': 0},
{'donor-country': 'POL', 'name': 'unv', 'value': 0},
{'donor-country': 'POL', 'name': 'cost sharing', 'value': 628927},
{'donor-country': 'POL', 'name': 'thematic trust funds', 'value': 0},
{'donor-country': 'POL', 'name': 'non-core', 'value': 628927},
{'donor-country': 'POL', 'name': 'special activities', 'value': 0},
{'donor-country': 'KWT', 'name': 'core', 'value': 570000},
{'donor-country': 'KWT', 'name': 'trust funds', 'value': 0},
{'donor-country': 'KWT', 'name': 'unv', 'value': 0},
{'donor-country': 'KWT', 'name': 'cost sharing', 'value': 10616797},
{'donor-country': 'KWT', 'name': 'thematic trust funds', 'value': 0},
{'donor-country': 'KWT', 'name': 'non-core', 'value': 10616797},
{'donor-country': 'KWT', 'name': 'special activities', 'value': 0},
{'donor-country': 'FUNDS_GFATM', 'name': 'core', 'value': 0},
{'donor-country': 'FUNDS_GFATM', 'name': 'trust funds', 'value': 0},
{'donor-country': 'FUNDS_GFATM', 'name': 'unv', 'value': 0},
{'donor-country': 'FUNDS_GFATM', 'name': 'cost sharing', 'value': 0},
{'donor-country': 'FUNDS_GFATM', 'name': 'thematic trust funds', 'value': 0},
{'donor-country': 'FUNDS_GFATM', 'name': 'non-core', 'value': 0},
{'donor-country': 'FUNDS_GFATM', 'name': 'special activities', 'value': 0},
{'donor-country': 'TGO', 'name': 'core', 'value': 0},
{'donor-country': 'TGO', 'name': 'trust funds', 'value': 0},
{'donor-country': 'TGO', 'name': 'unv', 'value': 0},
{'donor-country': 'TGO', 'name': 'cost sharing', 'value': 161815},
{'donor-country': 'TGO', 'name': 'thematic trust funds', 'value': 0},
{'donor-country': 'TGO', 'name': 'non-core', 'value': 161815},
{'donor-country': 'TGO', 'name': 'special activities', 'value': 0},
{'donor-country': 'CYM', 'name': 'core', 'value': 0},
{'donor-country': 'CYM', 'name': 'trust funds', 'value': 0},
{'donor-country': 'CYM', 'name': 'unv', 'value': 0},
{'donor-country': 'CYM', 'name': 'cost sharing', 'value': 0},
{'donor-country': 'CYM', 'name': 'thematic trust funds', 'value': 0},
{'donor-country': 'CYM', 'name': 'non-core', 'value': 0},
{'donor-country': 'CYM', 'name': 'special activities', 'value': 0},
{'donor-country': 'EST', 'name': 'core', 'value': 74728},
{'donor-country': 'EST', 'name': 'trust funds', 'value': 0},
{'donor-country': 'EST', 'name': 'unv', 'value': 0},
{'donor-country': 'EST', 'name': 'cost sharing', 'value': 0},
{'donor-country': 'EST', 'name': 'thematic trust funds', 'value': 0},
{'donor-country': 'EST', 'name': 'non-core', 'value': 0},
{'donor-country': 'EST', 'name': 'special activities', 'value': 0},
{'donor-country': 'MWI', 'name': 'core', 'value': 0},
{'donor-country': 'MWI', 'name': 'trust funds', 'value': 0},
{'donor-country': 'MWI', 'name': 'unv', 'value': 0},
{'donor-country': 'MWI', 'name': 'cost sharing', 'value': 0},
{'donor-country': 'MWI', 'name': 'thematic trust funds', 'value': 0},
{'donor-country': 'MWI', 'name': 'non-core', 'value': 0},
{'donor-country': 'MWI', 'name': 'special activities', 'value': 0},
{'donor-country': 'ESP', 'name': 'core', 'value': 2765974},
{'donor-country': 'ESP', 'name': 'trust funds', 'value': 1980276},
{'donor-country': 'ESP', 'name': 'unv', 'value': 0},
{'donor-country': 'ESP', 'name': 'cost sharing', 'value': 811978},
{'donor-country': 'ESP', 'name': 'thematic trust funds', 'value': 32987},
{'donor-country': 'ESP', 'name': 'non-core', 'value': 2825241},
{'donor-country': 'ESP', 'name': 'special activities', 'value': 0},
{'donor-country': 'IRQ', 'name': 'core', 'value': 500000},
{'donor-country': 'IRQ', 'name': 'trust funds', 'value': 5000},
{'donor-country': 'IRQ', 'name': 'unv', 'value': 0},
{'donor-country': 'IRQ', 'name': 'cost sharing', 'value': 2542435},
{'donor-country': 'IRQ', 'name': 'thematic trust funds', 'value': 0},
{'donor-country': 'IRQ', 'name': 'non-core', 'value': 2547435},
{'donor-country': 'IRQ', 'name': 'special activities', 'value': 0},
{'donor-country': 'SLV', 'name': 'core', 'value': 0},
{'donor-country': 'SLV', 'name': 'trust funds', 'value': 0},
{'donor-country': 'SLV', 'name': 'unv', 'value': 0},
{'donor-country': 'SLV', 'name': 'cost sharing', 'value': 37847822},
{'donor-country': 'SLV', 'name': 'thematic trust funds', 'value': 0},
{'donor-country': 'SLV', 'name': 'non-core', 'value': 37847822},
{'donor-country': 'SLV', 'name': 'special activities', 'value': 0},
{'donor-country': 'MLI', 'name': 'core', 'value': 0},
{'donor-country': 'MLI', 'name': 'trust funds', 'value': 0},
{'donor-country': 'MLI', 'name': 'unv', 'value': 0},
{'donor-country': 'MLI', 'name': 'cost sharing', 'value': 1367884},
{'donor-country': 'MLI', 'name': 'thematic trust funds', 'value': 0},
{'donor-country': 'MLI', 'name': 'non-core', 'value': 1367884},
{'donor-country': 'MLI', 'name': 'special activities', 'value': 0},
{'donor-country': 'VNM', 'name': 'core', 'value': 29000},
{'donor-country': 'VNM', 'name': 'trust funds', 'value': 0},
{'donor-country': 'VNM', 'name': 'unv', 'value': 0},
{'donor-country': 'VNM', 'name': 'cost sharing', 'value': 0},
{'donor-country': 'VNM', 'name': 'thematic trust funds', 'value': 0},
{'donor-country': 'VNM', 'name': 'non-core', 'value': 0},
{'donor-country': 'VNM', 'name': 'special activities', 'value': 0},
{'donor-country': 'IRL', 'name': 'core', 'value': 11691884},
{'donor-country': 'IRL', 'name': 'trust funds', 'value': 453971},
{'donor-country': 'IRL', 'name': 'unv', 'value': 131750},
{'donor-country': 'IRL', 'name': 'cost sharing', 'value': 2935864},
{'donor-country': 'IRL', 'name': 'thematic trust funds', 'value': 66313},
{'donor-country': 'IRL', 'name': 'non-core', 'value': 4300653},
{'donor-country': 'IRL', 'name': 'special activities', 'value': 712755},
{'donor-country': 'IRN', 'name': 'core', 'value': 0},
{'donor-country': 'IRN', 'name': 'trust funds', 'value': 0},
{'donor-country': 'IRN', 'name': 'unv', 'value': 0},
{'donor-country': 'IRN', 'name': 'cost sharing', 'value': 207651},
{'donor-country': 'IRN', 'name': 'thematic trust funds', 'value': 0},
{'donor-country': 'IRN', 'name': 'non-core', 'value': 207651},
{'donor-country': 'IRN', 'name': 'special activities', 'value': 0},
{'donor-country': 'PNG', 'name': 'core', 'value': 0},
{'donor-country': 'PNG', 'name': 'trust funds', 'value': 0},
{'donor-country': 'PNG', 'name': 'unv', 'value': 0},
{'donor-country': 'PNG', 'name': 'cost sharing', 'value': -45490},
{'donor-country': 'PNG', 'name': 'thematic trust funds', 'value': 0},
{'donor-country': 'PNG', 'name': 'non-core', 'value': -45490},
{'donor-country': 'PNG', 'name': 'special activities', 'value': 0},
{'donor-country': 'PAN', 'name': 'core', 'value': 0},
{'donor-country': 'PAN', 'name': 'trust funds', 'value': 0},
{'donor-country': 'PAN', 'name': 'unv', 'value': 0},
{'donor-country': 'PAN', 'name': 'cost sharing', 'value': 13129185},
{'donor-country': 'PAN', 'name': 'thematic trust funds', 'value': 0},
{'donor-country': 'PAN', 'name': 'non-core', 'value': 13129185},
{'donor-country': 'PAN', 'name': 'special activities', 'value': 0},
{'donor-country': 'BHS', 'name': 'core', 'value': 0},
{'donor-country': 'BHS', 'name': 'trust funds', 'value': 0},
{'donor-country': 'BHS', 'name': 'unv', 'value': 0},
{'donor-country': 'BHS', 'name': 'cost sharing', 'value': 0},
{'donor-country': 'BHS', 'name': 'thematic trust funds', 'value': 0},
{'donor-country': 'BHS', 'name': 'non-core', 'value': 0},
{'donor-country': 'BHS', 'name': 'special activities', 'value': 0},
{'donor-country': 'SLB', 'name': 'core', 'value': 0},
{'donor-country': 'SLB', 'name': 'trust funds', 'value': 0},
{'donor-country': 'SLB', 'name': 'unv', 'value': 0},
{'donor-country': 'SLB', 'name': 'cost sharing', 'value': 0},
{'donor-country': 'SLB', 'name': 'thematic trust funds', 'value': 0},
{'donor-country': 'SLB', 'name': 'non-core', 'value': 0},
{'donor-country': 'SLB', 'name': 'special activities', 'value': 0},
{'donor-country': 'NZL', 'name': 'core', 'value': 6552007},
{'donor-country': 'NZL', 'name': 'trust funds', 'value': 0},
{'donor-country': 'NZL', 'name': 'unv', 'value': 0},
{'donor-country': 'NZL', 'name': 'cost sharing', 'value': 131771},
{'donor-country': 'NZL', 'name': 'thematic trust funds', 'value': 40258},
{'donor-country': 'NZL', 'name': 'non-core', 'value': 172029},
{'donor-country': 'NZL', 'name': 'special activities', 'value': 0},
{'donor-country': 'MCO', 'name': 'core', 'value': 0},
{'donor-country': 'MCO', 'name': 'trust funds', 'value': 191467},
{'donor-country': 'MCO', 'name': 'unv', 'value': 0},
{'donor-country': 'MCO', 'name': 'cost sharing', 'value': 3996},
{'donor-country': 'MCO', 'name': 'thematic trust funds', 'value': 0},
{'donor-country': 'MCO', 'name': 'non-core', 'value': 195463},
{'donor-country': 'MCO', 'name': 'special activities', 'value': 0},
{'donor-country': 'JPN', 'name': 'core', 'value': 80472261},
{'donor-country': 'JPN', 'name': 'trust funds', 'value': 28165},
{'donor-country': 'JPN', 'name': 'unv', 'value': 1436080},
{'donor-country': 'JPN', 'name': 'cost sharing', 'value': 266022080},
{'donor-country': 'JPN', 'name': 'thematic trust funds', 'value': 5706344},
{'donor-country': 'JPN', 'name': 'non-core', 'value': 273192669},
{'donor-country': 'JPN', 'name': 'special activities', 'value': 0},
{'donor-country': 'KGZ', 'name': 'core', 'value': 0},
{'donor-country': 'KGZ', 'name': 'trust funds', 'value': 0},
{'donor-country': 'KGZ', 'name': 'unv', 'value': 0},
{'donor-country': 'KGZ', 'name': 'cost sharing', 'value': -910},
{'donor-country': 'KGZ', 'name': 'thematic trust funds', 'value': 0},
{'donor-country': 'KGZ', 'name': 'non-core', 'value': -910},
{'donor-country': 'KGZ', 'name': 'special activities', 'value': 0},
{'donor-country': 'ARM', 'name': 'core', 'value': 0},
{'donor-country': 'ARM', 'name': 'trust funds', 'value': 0},
{'donor-country': 'ARM', 'name': 'unv', 'value': 0},
{'donor-country': 'ARM', 'name': 'cost sharing', 'value': 4982631},
{'donor-country': 'ARM', 'name': 'thematic trust funds', 'value': 0},
{'donor-country': 'ARM', 'name': 'non-core', 'value': 4982631},
{'donor-country': 'ARM', 'name': 'special activities', 'value': 0},
{'donor-country': 'UGA', 'name': 'core', 'value': 0},
{'donor-country': 'UGA', 'name': 'trust funds', 'value': 0},
{'donor-country': 'UGA', 'name': 'unv', 'value': 0},
{'donor-country': 'UGA', 'name': 'cost sharing', 'value': 0},
{'donor-country': 'UGA', 'name': 'thematic trust funds', 'value': 0},
{'donor-country': 'UGA', 'name': 'non-core', 'value': 0},
{'donor-country': 'UGA', 'name': 'special activities', 'value': 0},
{'donor-country': 'ARE', 'name': 'core', 'value': 324000},
{'donor-country': 'ARE', 'name': 'trust funds', 'value': 20000},
{'donor-country': 'ARE', 'name': 'unv', 'value': 0},
{'donor-country': 'ARE', 'name': 'cost sharing', 'value': 1400733},
{'donor-country': 'ARE', 'name': 'thematic trust funds', 'value': 0},
{'donor-country': 'ARE', 'name': 'non-core', 'value': 1420733},
{'donor-country': 'ARE', 'name': 'special activities', 'value': 0},
{'donor-country': 'ARG', 'name': 'core', 'value': 0},
{'donor-country': 'ARG', 'name': 'trust funds', 'value': 4894},
{'donor-country': 'ARG', 'name': 'unv', 'value': 179300},
{'donor-country': 'ARG', 'name': 'cost sharing', 'value': 247308670},
{'donor-country': 'ARG', 'name': 'thematic trust funds', 'value': 0},
{'donor-country': 'ARG', 'name': 'non-core', 'value': 247492864},
{'donor-country': 'ARG', 'name': 'special activities', 'value': 0},
{'donor-country': 'SDN', 'name': 'core', 'value': 0},
{'donor-country': 'SDN', 'name': 'trust funds', 'value': 0},
{'donor-country': 'SDN', 'name': 'unv', 'value': 0},
{'donor-country': 'SDN', 'name': 'cost sharing', 'value': -3123},
{'donor-country': 'SDN', 'name': 'thematic trust funds', 'value': 0},
{'donor-country': 'SDN', 'name': 'non-core', 'value': -3123},
{'donor-country': 'SDN', 'name': 'special activities', 'value': 0},
{'donor-country': 'BHR', 'name': 'core', 'value': 0},
{'donor-country': 'BHR', 'name': 'trust funds', 'value': 0},
{'donor-country': 'BHR', 'name': 'unv', 'value': 0},
{'donor-country': 'BHR', 'name': 'cost sharing', 'value': -38168},
{'donor-country': 'BHR', 'name': 'thematic trust funds', 'value': 0},
{'donor-country': 'BHR', 'name': 'non-core', 'value': -38168},
{'donor-country': 'BHR', 'name': 'special activities', 'value': 0},
{'donor-country': 'HUN', 'name': 'core', 'value': 0},
{'donor-country': 'HUN', 'name': 'trust funds', 'value': 0},
{'donor-country': 'HUN', 'name': 'unv', 'value': 0},
{'donor-country': 'HUN', 'name': 'cost sharing', 'value': 25000},
{'donor-country': 'HUN', 'name': 'thematic trust funds', 'value': 0},
{'donor-country': 'HUN', 'name': 'non-core', 'value': 25000},
{'donor-country': 'HUN', 'name': 'special activities', 'value': 0},
{'donor-country': 'NRU', 'name': 'core', 'value': 0},
{'donor-country': 'NRU', 'name': 'trust funds', 'value': 0},
{'donor-country': 'NRU', 'name': 'unv', 'value': 0},
{'donor-country': 'NRU', 'name': 'cost sharing', 'value': 0},
{'donor-country': 'NRU', 'name': 'thematic trust funds', 'value': 0},
{'donor-country': 'NRU', 'name': 'non-core', 'value': 0},
{'donor-country': 'NRU', 'name': 'special activities', 'value': 0},
{'donor-country': 'CUB', 'name': 'core', 'value': 0},
{'donor-country': 'CUB', 'name': 'trust funds', 'value': 0},
{'donor-country': 'CUB', 'name': 'unv', 'value': 0},
{'donor-country': 'CUB', 'name': 'cost sharing', 'value': 0},
{'donor-country': 'CUB', 'name': 'thematic trust funds', 'value': 0},
{'donor-country': 'CUB', 'name': 'non-core', 'value': 0},
{'donor-country': 'CUB', 'name': 'special activities', 'value': 0},
]
